import { Meteor } from 'meteor/meteor';
import Announcements from '../lib/models/Announcements';
import BlobMappings from '../lib/models/BlobMappings';
import ChatMessages from '../lib/models/ChatMessages';
import ChatNotifications from '../lib/models/ChatNotifications';
import DiscordCache from '../lib/models/DiscordCache';
import DiscordRoleGrants from '../lib/models/DiscordRoleGrants';
import DocumentActivities from '../lib/models/DocumentActivities';
import Documents from '../lib/models/Documents';
import FeatureFlags from '../lib/models/FeatureFlags';
import FolderPermissions from '../lib/models/FolderPermissions';
import Guesses from '../lib/models/Guesses';
import Hunts from '../lib/models/Hunts';
import PendingAnnouncements from '../lib/models/PendingAnnouncements';
import Puzzles from '../lib/models/Puzzles';
import Servers from '../lib/models/Servers';
import Settings from '../lib/models/Settings';
import Tags from '../lib/models/Tags';
import CallHistories from '../lib/models/mediasoup/CallHistories';
import ConnectAcks from '../lib/models/mediasoup/ConnectAcks';
import ConnectRequests from '../lib/models/mediasoup/ConnectRequests';
import ConsumerAcks from '../lib/models/mediasoup/ConsumerAcks';
import Consumers from '../lib/models/mediasoup/Consumers';
import PeerRemoteMutes from '../lib/models/mediasoup/PeerRemoteMutes';
import Peers from '../lib/models/mediasoup/Peers';
import ProducerClients from '../lib/models/mediasoup/ProducerClients';
import ProducerServers from '../lib/models/mediasoup/ProducerServers';
import Rooms from '../lib/models/mediasoup/Rooms';
import Routers from '../lib/models/mediasoup/Routers';
import TransportRequests from '../lib/models/mediasoup/TransportRequests';
import TransportStates from '../lib/models/mediasoup/TransportStates';
import Transports from '../lib/models/mediasoup/Transports';
import Announcement from '../lib/schemas/Announcement';
import BlobMapping from '../lib/schemas/BlobMapping';
import ChatMessage from '../lib/schemas/ChatMessage';
import ChatNotification from '../lib/schemas/ChatNotification';
import DiscordCacheSchema from '../lib/schemas/DiscordCache';
import DiscordRoleGrant from '../lib/schemas/DiscordRoleGrant';
import DocumentSchema from '../lib/schemas/Document';
import DocumentActivity from '../lib/schemas/DocumentActivity';
import FeatureFlag from '../lib/schemas/FeatureFlag';
import FolderPermission from '../lib/schemas/FolderPermission';
import Guess from '../lib/schemas/Guess';
import Hunt from '../lib/schemas/Hunt';
import PendingAnnouncement from '../lib/schemas/PendingAnnouncement';
import Puzzle from '../lib/schemas/Puzzle';
import Server from '../lib/schemas/Server';
import Setting from '../lib/schemas/Setting';
import Tag from '../lib/schemas/Tag';
import User from '../lib/schemas/User';
import CallHistory from '../lib/schemas/mediasoup/CallHistory';
import ConnectAck from '../lib/schemas/mediasoup/ConnectAck';
import ConnectRequest from '../lib/schemas/mediasoup/ConnectRequest';
import Consumer from '../lib/schemas/mediasoup/Consumer';
import ConsumerAck from '../lib/schemas/mediasoup/ConsumerAck';
import Peer from '../lib/schemas/mediasoup/Peer';
import PeerRemoteMute from '../lib/schemas/mediasoup/PeerRemoteMute';
import ProducerClient from '../lib/schemas/mediasoup/ProducerClient';
import ProducerServer from '../lib/schemas/mediasoup/ProducerServer';
import Room from '../lib/schemas/mediasoup/Room';
import Router from '../lib/schemas/mediasoup/Router';
import Transport from '../lib/schemas/mediasoup/Transport';
import TransportRequest from '../lib/schemas/mediasoup/TransportRequest';
import TransportState from '../lib/schemas/mediasoup/TransportState';
import APIKeys from './models/APIKeys';
import Blobs from './models/Blobs';
import CallActivities from './models/CallActivities';
import DriveActivityLatests from './models/DriveActivityLatests';
import HuntFolders from './models/HuntFolders';
import Locks from './models/Locks';
import Subscribers from './models/Subscribers';
import UploadTokens from './models/UploadTokens';
import APIKey from './schemas/APIKey';
import Blob from './schemas/Blob';
import CallActivity from './schemas/CallActivity';
import DriveActivityLatest from './schemas/DriveActivityLatest';
import HuntFolder from './schemas/HuntFolder';
import Lock from './schemas/Lock';
import Subscriber from './schemas/Subscriber';
import UploadToken from './schemas/UploadToken';

Announcements.attachSchema(Announcement);
BlobMappings.attachSchema(BlobMapping);
ChatMessages.attachSchema(ChatMessage);
ChatNotifications.attachSchema(ChatNotification);
DiscordCache.attachSchema(DiscordCacheSchema);
DiscordRoleGrants.attachSchema(DiscordRoleGrant);
DocumentActivities.attachSchema(DocumentActivity);
Documents.attachSchema(DocumentSchema);
FeatureFlags.attachSchema(FeatureFlag);
FolderPermissions.attachSchema(FolderPermission);
Guesses.attachSchema(Guess);
Hunts.attachSchema(Hunt);
Meteor.users.attachSchema(User);
PendingAnnouncements.attachSchema(PendingAnnouncement);
Puzzles.attachSchema(Puzzle);
Servers.attachSchema(Server);
Settings.attachSchema(Setting);
Tags.attachSchema(Tag);
CallHistories.attachSchema(CallHistory);
ConnectAcks.attachSchema(ConnectAck);
ConnectRequests.attachSchema(ConnectRequest);
ConsumerAcks.attachSchema(ConsumerAck);
Consumers.attachSchema(Consumer);
PeerRemoteMutes.attachSchema(PeerRemoteMute);
Peers.attachSchema(Peer);
ProducerClients.attachSchema(ProducerClient);
ProducerServers.attachSchema(ProducerServer);
Rooms.attachSchema(Room);
Routers.attachSchema(Router);
TransportRequests.attachSchema(TransportRequest);
Transports.attachSchema(Transport);
TransportStates.attachSchema(TransportState);
APIKeys.attachSchema(APIKey);
Blobs.attachSchema(Blob);
CallActivities.attachSchema(CallActivity);
DriveActivityLatests.attachSchema(DriveActivityLatest);
HuntFolders.attachSchema(HuntFolder);
Locks.attachSchema(Lock);
Subscribers.attachSchema(Subscriber);
UploadTokens.attachSchema(UploadToken);
