hunt_2015_puzzles = [
  { id: "p681", title: "Workshop Meta Meta", answer: "STEAMLAB", tags: ["meta", "meta:workshop"], url: "http://www.20000puzzles.com/puzzle/workshop_meta_meta"},
  { id: "p694", title: "Steam Lab", answer: "(COMPLETED)", tags: ["interaction", "meta:workshop"], url: "http://www.20000puzzles.com/puzzle/workshop_meta_meta/HGqxO8M8HbxCFwIo.html"},
  { id: "p730", title: "Ocean Meta Meta", answer: "SHIPWRECK", tags: ["meta", "meta:ocean"], url: "http://20000puzzles.com/accounts/login/?next=/puzzle/ocean_meta_meta/"},
  { id: "p804", title: "Atlantis Meta Meta", answer: "TOP OF TALLEST TOWER", tags: ["meta", "meta:atlantis"], url: "http://www.20000puzzles.com/puzzle/atlantis_meta_meta/"},

  { id: "r79", title: "Spotted Tower", answer: "ENCHANTED PANACEA", tags: ["meta", "meta:atlantis", "meta:spotted-tower"], url: "http://www.20000puzzles.com/puzzle/spotted_tower_meta"},
  { id: "p779", title: "Topsy-Turvy", answer: "BLINDNESS", tags: ["meta:spotted-tower"], url: "http://www.20000puzzles.com/puzzle/topsy_turvy/"},
  { id: "p784", title: "Hunt-Life 3 Confirmed", answer: "dislocated tailbone", tags: ["meta:spotted-tower"], url: "http://www.20000puzzles.com/puzzle/hunt_life_3_confirmed/"},
  { id: "p788", title: "Atlantean Graves", answer: "TRIPLE DECAPITATION", tags: ["meta:spotted-tower"], url: "http://www.20000puzzles.com/puzzle/atlantean_graves/"},
  { id: "p791", title: "Foamy", answer: "voicelessness", tags: ["meta:spotted-tower"], url: "http://www.20000puzzles.com/puzzle/foamy/"},
  { id: "p798", title: "Benny Lava", answer: "ANAL BLEEDING", tags: ["meta:spotted-tower"], url: "http://www.20000puzzles.com/puzzle/benny_lava/"},

  { id: "r81", title: "Golden Tower", answer: "TRIDENT OF HARMONY", tags: ["meta", "meta:atlantis", "meta:golden-tower"], url: "http://www.20000puzzles.com/puzzle/golden_tower_meta/"},
  { id: "p785", title: "Tantalum", answer: "Xena", tags: ["meta:golden-tower"], url: "http://www.20000puzzles.com/puzzle/tantalum/"},
  { id: "p792", title: "Check Out This Sticked Asiatic Music", answer: "hideout", tags: ["meta:golden-tower"], url: "http://www.20000puzzles.com/puzzle/check_out_this_sticked_asiatic_music/"},
  { id: "p795", title: "Practice in Theory", answer: "solzhenitsyn", tags: ["meta:golden-tower"], url: "http://www.20000puzzles.com/puzzle/practice_in_theory/"},
  { id: "p797", title: "Cryptic Golf", answer: "mono", tags: ["meta:golden-tower"], url: "http://www.20000puzzles.com/puzzle/cryptic_golf/"},
  { id: "p801", title: "Mashup", answer: "FLOWER", tags: ["meta:golden-tower"], url: "http://www.20000puzzles.com/puzzle/mashup/"},
  { id: "p803", title: "Connect the Ducks", answer: "BRIDE TO BE", tags: ["meta:golden-tower"], url: "http://www.20000puzzles.com/puzzle/connect_the_ducks/"},

  { id: "r80", title: "Spiky Tower", answer: "FAERIE CORNUCOPIA", tags: ["meta", "meta:atlantis", "meta:spiky-tower"], url: "http://www.20000puzzles.com/puzzle/spiky_tower_meta/"},
  { id: "p773", title: "A Case of the Monday Crosswords", answer: "ROBBERIES", tags: ["meta:spiky-tower"], url: "http://www.20000puzzles.com/puzzle/a_case_of_the_monday_crosswords/"},
  { id: "p777", title: "Lead Right", answer: "GRAPHITE", tags: ["meta:spiky-tower"], url: "http://www.20000puzzles.com/puzzle/lead_right/"},
  { id: "p786", title: "Quodlibet", answer: "PRACTICE", tags: ["meta:spiky-tower"], url: "http://www.20000puzzles.com/puzzle/quodlibet/"},
  { id: "p796", title: "UKACD", answer: "FRUMPISH", tags: ["meta:spiky-tower"], url: "http://www.20000puzzles.com/puzzle/ukacd/"},
  { id: "p789", title: "Cryptochains", answer: "FRAYED", tags: ["meta:spiky-tower"], url: "http://www.20000puzzles.com/puzzle/cryptochains/"},
  { id: "p793", title: "The Sun Will Come Out", answer: "shopworker", tags: ["meta:spiky-tower"], url: "http://www.20000puzzles.com/puzzle/the_sun_will_come_out/"},
  { id: "p800", title: "Read Between the Lines", answer: "ROILING", tags: ["meta:spiky-tower"], url: "http://www.20000puzzles.com/puzzle/read_between_the_lines/"},
  { id: "p802", title: "Follow the Bees!", answer: "benefice", tags: ["meta:spiky-tower"], url: "http://www.20000puzzles.com/puzzle/follow_the_bees/"},
  { id: "p782", title: "Floating Crossword", answer: "KATHLEEN", tags: ["meta:spiky-tower"], url: "http://www.20000puzzles.com/puzzle/floating_crossword/"},

  { id: "r78", title: "Colorful Tower", answer: "IMMORTAL IRON KEEL", tags: ["meta", "meta:atlantis", "meta:colorful-tower"], url: "http://www.20000puzzles.com/puzzle/colorful_tower_meta/"},
  { id: "p772", title: "Smiling Vessel", answer: "GAME", tags: ["meta:colorful-tower"], url: "http://www.20000puzzles.com/puzzle/smiling_vessel/"},
  { id: "p776", title: "Image", answer: "holstein", tags: ["meta:colorful-tower"], url: "http://www.20000puzzles.com/puzzle/image/"},
  { id: "p783", title: "Blue Bomber", answer: "HUMAN", tags: ["meta:colorful-tower"], url: "http://www.20000puzzles.com/puzzle/blue_bomber/"},
  { id: "p787", title: "Steve's Parable", answer: "PINE", tags: ["meta:colorful-tower"], url: "http://www.20000puzzles.com/puzzle/steves_parable/"},
  { id: "p790", title: "Time and Place", answer: "GOPHER", tags: ["meta:colorful-tower"], url: "http://www.20000puzzles.com/puzzle/time_amp_place/"},
  { id: "p794", title: "A Push in the Right Direction", answer: "HERO", tags: ["meta:colorful-tower"], url: "http://www.20000puzzles.com/puzzle/a_push_in_the_right_direction/"},
  { id: "p799", title: "Suns of China", answer: "STAR", tags: ["meta:colorful-tower"], url: "http://www.20000puzzles.com/puzzle/suns_of_china/"},

  { id: "r77", title: "Graveyard", answer: "MECHANICAL SEA MONSTER", tags: ["meta", "meta:graveyard"], url: "http://www.20000puzzles.com/puzzle/graveyard_meta/"},
  { id: "p750", title: "Shark Blood", answer: "winner", tags: ["meta:graveyard"], url: "http://www.20000puzzles.com/puzzle/shark_blood/"},
  { id: "p752", title: "Welcome to Dead Waters", answer: "summer", tags: ["meta:graveyard"], url: "http://www.20000puzzles.com/puzzle/welcome_to_dead_waters/"},
  { id: "p753", title: "Say Cheese and Dive!", answer: "CURLUP", tags: ["meta:graveyard"], url: "http://www.20000puzzles.com/puzzle/say_cheese_and_dive/"},
  { id: "p754", title: "Let's Get Submersible!", answer: "smspommern", tags: ["meta:graveyard"], url: "http://www.20000puzzles.com/puzzle/lets_get_submersible/"},
  { id: "p756", title: "Night of the Living Kraken", answer: "stirfry", tags: ["meta:graveyard"], url: "http://www.20000puzzles.com/puzzle/night_of_the_living_kraken/"},
  { id: "p758", title: "The Curse of the Atlantean's Tomb", answer: "bigsur", tags: ["meta:graveyard"], url: "http://www.20000puzzles.com/puzzle/the_curse_of_the_atlanteans_tomb/"},
  { id: "p761", title: "Stay Out of the Trench", answer: "KERFUFFLE", tags: ["meta:graveyard"], url: "http://www.20000puzzles.com/puzzle/stay_out_of_the_trench/"},

  // Aquatic acquaintances
  { id: "p700", title: "Captain Planet", answer: "RECYCLE CONTENT", tags: ["group:aquatic-acquaintances"], url: "http://www.20000puzzles.com/puzzle/captain_planet/"},
  { id: "p680", title: "Spongebob", answer: "UNTANGLE LINES", tags: ["group:aquatic-acquaintances"], url: "http://www.20000puzzles.com/puzzle/spongebob/"},
  { id: "p742", title: "Dory", answer: "look behind you", tags: ["group:aquatic-acquaintances"], url: "http://www.20000puzzles.com/puzzle/dory/"},
  { id: "p742", title: "Cthulhu", answer: "FEED ME YOUR SOLES", tags: ["group:aquatic-acquaintances"], url: "http://www.20000puzzles.com/puzzle/cthulhu/"},

  // Treasure chest
  { id: "r76", title: "Treasure Chest", answer: "MANTA RAY VISION", tags: ["meta", "meta:treasure-chest"], url: "http://www.20000puzzles.com/puzzle/treasure_chest_meta"},
  { id: "p720", title: "Cube", answer: "MCGONAGALL", tags: ["meta:treasure-chest"], url: "http://www.20000puzzles.com/puzzle/cube/"},
  { id: "p721", title: "Game", answer: "CONSOLATION", tags: ["meta:treasure-chest"], url: "http://www.20000puzzles.com/puzzle/game"},
  { id: "p722", title: "Knit Square", answer: "gladwell", tags: ["meta:treasure-chest"], url: "http://www.20000puzzles.com/puzzle/knit_square"},
  { id: "p723", title: "Ropes", answer: "buffalo", tags: ["meta:treasure-chest"], url: "http://www.20000puzzles.com/puzzle/ropes"},
  { id: "p724", title: "Paper Jigsaw", answer: "the spirits within", tags: ["meta:treasure-chest"], url: "http://www.20000puzzles.com/puzzle/paper_jigsaw"},
  { id: "p732", title: "Locks", answer: "LISTENING", tags: ["meta:treasure-chest"], url: "http://www.20000puzzles.com/puzzle/locks"},
  { id: "p726", title: "Wood", answer: "GAP", tags: ["meta:treasure-chest"], url: "http://www.20000puzzles.com/puzzle/wood"},
  { id: "p727", title: "Coins", answer: "DRESDEN", tags: ["meta:treasure-chest"], url: "http://www.20000puzzles.com/puzzle/coins"},

  // Coral reef
  { id: "r73", title: "Coral Reef", answer: "ELECTRIC EEL POWER", tags: ["meta", "meta:coral-reef"], url: "http://www.20000puzzles.com/puzzle/coral_reef_meta/"},
  { id: "p675", title: "Hashi It Out", answer: "roses", tags: ["meta:coral-reef"], url: "http://www.20000puzzles.com/puzzle/hashi_it_out/"},
  { id: "p678", title: "Ariel's Scavenger Hunt", answer: "SERRA ANGEL", tags: ["scavenger-hunt","meta:coral-reef"], url: "http://www.20000puzzles.com/puzzle/ariels_scavenger_hunt"},
  { id: "p682", title: "A Puzzle Consisting Entirely of Random Anagrams", answer: "EIGHT BALL", tags: ["meta:coral-reef"], url: "http://www.20000puzzles.com/puzzle/a_puzzle_consisting_entirely_of_random_anagrams"},
  { id: "p685", title: "Jack and Jill or Janet", answer: "COMEDY", tags: ["meta:coral-reef"], url: "http://www.20000puzzles.com/puzzle/jack_and_jill_or_janet"},
  { id: "p688", title: "A Thousand Words", answer: "ELEPHANT", tags: ["meta:coral-reef"], url: "http://www.20000puzzles.com/puzzle/a_thousand_words"},
  { id: "p690", title: "Pipe", answer: "darn", tags: ["meta:coral-reef"], url: "http://www.20000puzzles.com/puzzle/pipe/"},
  { id: "p695", title: "Polyglot", answer: "MICHELANGELO", tags: ["meta:coral-reef"], url: "http://www.20000puzzles.com/puzzle/polyglot"},
  { id: "p698", title: "The 10,000 Puzzle Pyramid", answer: "robertelee", tags: ["meta:coral-reef"], url: "http://www.20000puzzles.com/puzzle/the_10_000_puzzle_pyramid"},

  // Pod of Dolphins
  { id: "r72", title: "Pod of Dolphins", answer: "BELUGA PAL", tags: ["meta", "meta:pod-of-dolphins"], url: "http://www.20000puzzles.com/puzzle/pod_of_dolphins_meta"},
  { id: "p674", title: "Per Verse Poetry", answer: "CITYGATES", tags: ["meta:pod-of-dolphins"], url: "http://www.20000puzzles.com/puzzle/per_verse_poetry"},
  { id: "p677", title: "Representative Characters", answer: "IMPULSIVE", tags: ["meta:pod-of-dolphins"], url: "http://www.20000puzzles.com/puzzle/representative_characters/"},
  { id: "p684", title: "Constraint Chef", answer: "CLICK SPAM", tags: ["cook-for-hq","meta:pod-of-dolphins"], url: "http://www.20000puzzles.com/puzzle/constraint_chef"},
  { id: "p691", title: "Something Looks Fishy", answer: "BAPTISTRY", tags: ["meta:pod-of-dolphins"], url: "http://www.20000puzzles.com/puzzle/something_looks_fishy"},
  { id: "p699", title: "Field Trip", answer: "LEVIATHAN", tags: ["meta:pod-of-dolphins"], url: "http://www.20000puzzles.com/puzzle/field_trip"},
  { id: "p703", title: "MiT MYSTERY HUNT", answer: "police car", tags: ["meta:pod-of-dolphins"], url: "http://www.20000puzzles.com/puzzle/mit_mystery_hunt"},
  { id: "p710", title: "Choose Your Language", answer: "COUP DETAT", tags: ["meta:pod-of-dolphins"], url: "http://www.20000puzzles.com/puzzle/choose_your_language/"},
  { id: "p717", title: "It's Play Time", answer: "SFORZANDO", tags: ["meta:pod-of-dolphins"], url: "http://www.20000puzzles.com/puzzle/its_play_time/"},
  { id: "p719", title: "Dr. Nautilus's Secret Notes", answer: "CARTWHEEL", tags: ["meta:pod-of-dolphins"], url: "http://www.20000puzzles.com/puzzle/dr_nautiluss_secret_notes/"},

  // School of fish (augh)
  { id: "r71", title: "School of Fish", answer: "SARDINE CANNONS", tags: ["meta", "meta:school-of-fish"], url: "http://www.20000puzzles.com/puzzle/school_of_fish_meta/"},
  { id: "p669", title: "Denizen of the Deep", answer: "OPERA", tags: ["meta:school-of-fish"], url: "http://www.20000puzzles.com/puzzle/denizen_of_the_deep"},
  { id: "p671", title: "Eh?", answer: "rant", tags: ["meta:school-of-fish"], url: "http://www.20000puzzles.com/puzzle/eh/"},
  { id: "p672", title: "Feeling Bluefin", answer: "STURGEON", tags: ["meta:school-of-fish"], url: "http://www.20000puzzles.com/puzzle/feeling_bluefin/"},
  { id: "p686", title: "Tournament", answer: "DRAFT", tags: ["meta:school-of-fish"], url: "http://www.20000puzzles.com/puzzle/tournament"},
  { id: "p687", title: "The Cat's Meow", answer: "DANGLE", tags: ["meta:school-of-fish"], url: "http://www.20000puzzles.com/puzzle/the_cats_meow/"},
  { id: "p689", title: "A Short Transmission", answer: "CLAN LAIRD", tags: ["meta:school-of-fish"], url: "http://www.20000puzzles.com/puzzle/a_short_transmission"},
  { id: "p692", title: "Hash", answer: "TUBA", tags: ["meta:school-of-fish"], url: "http://www.20000puzzles.com/puzzle/hash/"},
  { id: "p693", title: "Ready Set Go", answer: "stooge", tags: ["meta:school-of-fish"], url: "http://www.20000puzzles.com/puzzle/ready_set_go/"},
  { id: "p697", title: "Frequency Distribution Tank", answer: "CRASHER", tags: ["meta:school-of-fish"], url: "http://www.20000puzzles.com/puzzle/frequency_distribution_tank"},
  { id: "p701", title: "Headshots", answer: "REGENT", tags: ["meta:school-of-fish"], url: "http://www.20000puzzles.com/puzzle/headshots"},
  { id: "p702", title: "Watch Me Blow This!", answer: "Piper", tags: ["meta:school-of-fish"], url: "http://www.20000puzzles.com/puzzle/watch_me_blow_this/"},
  { id: "p704", title: "Blocks", answer: "ruble", tags: ["meta:school-of-fish"], url: "http://www.20000puzzles.com/puzzle/blocks/"},
  { id: "p705", title: "The Last Airbender", answer: "raptors", tags: ["meta:school-of-fish"], url: "http://www.20000puzzles.com/puzzle/the_last_airbender/"},
  { id: "p706", title: "Rid Fill", answer: "DYLAN", tags: ["meta:school-of-fish"], url: "http://www.20000puzzles.com/puzzle/rid_fill/"},
  { id: "p707", title: "Moves", answer: "SPARENET", tags: ["meta:school-of-fish"], url: "http://www.20000puzzles.com/puzzle/moves"},
  { id: "p708", title: "Twelve Grids of Pictures", answer: "PAWS", tags: ["meta:school-of-fish"], url: "http://www.20000puzzles.com/puzzle/twelve_grids_of_pictures/"},
  { id: "p709", title: "The Acerbic Sixteen", answer: "cred", tags: ["meta:school-of-fish"], url: "http://www.20000puzzles.com/puzzle/the_acerbic_sixteen"},
  { id: "p711", title: "This Story is Canon", answer: "BOUCHER", tags: ["meta:school-of-fish"], url: "http://www.20000puzzles.com/puzzle/this_story_is_canon/"},
  { id: "p712", title: "p1ctures", answer: "eking", tags: ["meta:school-of-fish"], url: "http://www.20000puzzles.com/puzzle/p1ctures/"},
  { id: "p713", title: "Tickle Me Pink", answer: "STOLEN", tags: ["meta:school-of-fish"], url: "http://www.20000puzzles.com/puzzle/tickle_me_pink/"},
  { id: "p714", title: "Memory Lane", answer: "SOAPED", tags: ["meta:school-of-fish"], url: "http://www.20000puzzles.com/puzzle/memory_lane"},
  { id: "p715", title: "Ride 'Em In", answer: "TOUGHEN", tags: ["meta:school-of-fish"], url: "http://www.20000puzzles.com/puzzle/ride_em_in/"},
  { id: "p716", title: "The Hidden City", answer: "limon", tags: ["meta:school-of-fish"], url: "http://www.20000puzzles.com/puzzle/the_hidden_city"},
  { id: "p718", title: "Trivia Round", answer: "MARBLE", tags: ["meta:school-of-fish"], url: "http://www.20000puzzles.com/puzzle/trivia_round/"},
  { id: "p729", title: "Go at It!", answer: "ISABEL", tags: ["meta:school-of-fish"], url: "http://www.20000puzzles.com/puzzle/go_at_it"},
  { id: "p731", title: "Goldfish Memory", answer: "BLAZER", tags: ["meta:school-of-fish"], url: "http://www.20000puzzles.com/puzzle/goldfish_memory/"},
  { id: "p733", title: "Bubbles", answer: "pikers", tags: ["meta:school-of-fish"], url: "http://www.20000puzzles.com/puzzle/bubbles"},
  { id: "p734", title: "Bookshelves", answer: "crowds", tags: ["meta:school-of-fish"], url: "http://www.20000puzzles.com/puzzle/bookshelves/"},
  { id: "p735", title: "Three's The Charm", answer: "amadeus", tags: ["meta:school-of-fish"], url: "http://www.20000puzzles.com/puzzle/threes_the_charm/"},
  { id: "p736", title: "Starfish", answer: "crook", tags: ["meta:school-of-fish"], url: "http://www.20000puzzles.com/puzzle/starfish"},
  { id: "p738", title: "Toasting the Bagel", answer: "SICK PORNO", tags: ["meta:school-of-fish"], url: "http://www.20000puzzles.com/puzzle/toasting_the_bagel/"},
  { id: "p740", title: "Rectangles", answer: "RAMBLES", tags: ["meta:school-of-fish"], url: "http://www.20000puzzles.com/puzzle/rectangles/"},
  { id: "p741", title: "FJF,S", answer: "freeing", tags: ["meta:school-of-fish"], url: "http://www.20000puzzles.com/puzzle/fjf_s/"},
  { id: "p743", title: "Fencing", answer: "LUNGE", tags: ["meta:school-of-fish"], url: "http://www.20000puzzles.com/puzzle/fencing"},
  { id: "p745", title: "Striptease", answer: "BARON", tags: ["meta:school-of-fish"], url: "http://www.20000puzzles.com/puzzle/striptease"},
  { id: "p746", title: "Siamese Quintuplets", answer: "elite", tags: ["meta:school-of-fish"], url: "http://www.20000puzzles.com/puzzle/siamese_quintuplets"},
  { id: "p747", title: "Not All There", answer: "cleaned", tags: ["meta:school-of-fish"], url: "http://www.20000puzzles.com/puzzle/not_all_there"},
  { id: "p744", title: "No Pluto", answer: "heartpin", tags: ["meta:school-of-fish"], url: "http://www.20000puzzles.com/puzzle/no_pluto/"},
  { id: "p748", title: "The Resistance", answer: "boone", tags: ["meta:school-of-fish"], url: "http://www.20000puzzles.com/puzzle/the_resistance/"},
  { id: "p751", title: "Go Fish", answer: "AHEAD", tags: ["meta:school-of-fish"], url: "http://www.20000puzzles.com/puzzle/go_fish"},
  { id: "p755", title: "Fill in the Blanks", answer: "serbia", tags: ["meta:school-of-fish"], url: "http://www.20000puzzles.com/puzzle/fill_in_the_blanks/"},
  { id: "p757", title: "A Toast", answer: "PAPERS", tags: ["meta:school-of-fish"], url: "http://www.20000puzzles.com/puzzle/a_toast/"},
  { id: "p759", title: "Be a Star!", answer: "triage", tags: ["meta:school-of-fish"], url: "http://www.20000puzzles.com/puzzle/be_a_star/"},
  { id: "p762", title: "I Know That's a Pisser Baby", answer: "ANKLES", tags: ["meta:school-of-fish"], url: "http://www.20000puzzles.com/puzzle/i_know_thats_a_pisser_baby/"},
  { id: "p763", title: "Word Fork", answer: "MICE", tags: ["meta:school-of-fish"], url: "http://www.20000puzzles.com/puzzle/word_fork/"},
  { id: "p764", title: "A Poem by Shell Silverstein", answer: "HAWKE", tags: ["meta:school-of-fish"], url: "http://www.20000puzzles.com/puzzle/a_poem_by_shell_silverstein/"},
  { id: "p765", title: "Even the Blossoming Flowers...", answer: "wraps", tags: ["meta:school-of-fish"], url: "http://www.20000puzzles.com/puzzle/even_the_blossoming_flowers/"},
  { id: "p766", title: "Spittle Loon", answer: "BARFED", tags: ["meta:school-of-fish"], url: "http://www.20000puzzles.com/puzzle/spittle_loon/"},
  { id: "p768", title: "Flat Containers", answer: "INTERNAL", tags: ["meta:school-of-fish"], url: "http://www.20000puzzles.com/puzzle/flat_containers"},
  { id: "p767", title: "The ____er of Men", answer: "OCTAL", tags: ["meta:school-of-fish"], url: "http://www.20000puzzles.com/puzzle/the_er_of_men"},
  { id: "p769", title: "The Wheels Go Round and Round", answer: "SEDAN", tags: ["meta:school-of-fish"], url: "http://www.20000puzzles.com/puzzle/the_wheels_go_round_and_round/"},
  { id: "p770", title: "Munchies", answer: "taco", tags: ["meta:school-of-fish"], url: "http://www.20000puzzles.com/puzzle/munchies/"},
  { id: "p771", title: "Back and Forth", answer: "colored ice", tags: ["meta:school-of-fish"], url: "http://www.20000puzzles.com/puzzle/back_and_forth/"},
  { id: "p774", title: "Encephelon", answer: "rotor set", tags: ["meta:school-of-fish"], url: "http://www.20000puzzles.com/puzzle/encephalon/"},
  { id: "p775", title: "Funny Shapes", answer: "LODGE", tags: ["meta:school-of-fish"], url: "http://www.20000puzzles.com/puzzle/funny_shapes/"},
  { id: "p778", title: "Les Faux Amis Valent Rien", answer: "others", tags: ["meta:school-of-fish"], url: "http://www.20000puzzles.com/puzzle/les_faux_amis_valent_rien/"},

  // Chemistry lab
  { id: "r70", title: "Chemistry Lab", answer: "COOL FUEL", tags: ["meta", "meta:chemistry-lab"], url: "http://www.20000puzzles.com/puzzle/chemistry_lab_meta"},
  { id: "p657", title: "Escape from the Classroom", answer: "FLOORMAT", tags: ["meta:chemistry-lab"], url: "http://www.20000puzzles.com/puzzle/escape_from_the_classroom"},
  { id: "p696", title: "Mythological Connections", answer: "DEWDROP", tags: ["meta:chemistry-lab"], url: "http://www.20000puzzles.com/puzzle/mythological_connections"},
  { id: "p676", title: "The Misspelled Insects", answer: "BLUE FINCH", tags: ["meta:chemistry-lab"], url: "http://www.20000puzzles.com/puzzle/the_misspelled_insects"},
  { id: "p679", title: "People and Places", answer: "BOAR THORAX", tags: ["meta:chemistry-lab"], url: "http://www.20000puzzles.com/puzzle/people_and_places"},
  { id: "p661", title: "Finsey Gillhone", answer: "GUN STOCKS", tags: ["meta:chemistry-lab"], url: "http://www.20000puzzles.com/puzzle/finsey_gillhone"},
  { id: "p656", title: "Wordsearches Are a Piece of Cake", answer: "STEW LUNCHES", tags: ["meta:chemistry-lab"], url: "http://www.20000puzzles.com/puzzle/wordsearches_are_a_piece_of_cake/"},
  { id: "p665", title: "Speak of the Devil Fruit", answer: "SEABEACHES", tags: ["meta:chemistry-lab"], url: "http://www.20000puzzles.com/puzzle/speak_of_the_devil_fruit/"},
  { id: "p662", title: "The Accumulator", answer: "LIVEMYRTLE", tags: ["meta:chemistry-lab"], url: "http://www.20000puzzles.com/puzzle/the_accumulator"},

  // Optics lab
  { id: "r69", title: "Optics Lab", answer: "PRISMATIC PERISCOPE", tags: ["meta", "meta:optics-lab"], url: "http://www.20000puzzles.com/puzzle/optics_lab_meta/"},
  { id: "p666", title: "This Puzzle Has No Errata", answer: "BLOOPER", tags: ["meta:optics-lab"], url: "http://www.20000puzzles.com/puzzle/this_puzzle_has_no_errata/"},
  { id: "p683", title: "Wait, What Did You Say?", answer: "VAMPIRE", tags: ["meta:optics-lab"], url: "http://www.20000puzzles.com/puzzle/wait_what_did_you_say"},
  { id: "p673", title: "Time Is Out of Joint", answer: "REPRISE", tags: ["meta:optics-lab"], url: "http://www.20000puzzles.com/puzzle/time_is_out_of_joint"},
  { id: "p670", title: "Wizardly Tales", answer: "Yahtzee", tags: ["meta:optics-lab"], url: "http://www.20000puzzles.com/puzzle/wizardly_tales"},
  { id: "p663", title: "Captain Ager's Puzzling Adventure", answer: "GRAPHIC", tags: ["meta:optics-lab"], url: "http://www.20000puzzles.com/puzzle/captain_agers_puzzling_adventure/"},
  { id: "p654", title: "Montages", answer: "itscool", tags: ["meta:optics-lab"], url: "http://www.20000puzzles.com/puzzle/montages/"},
  { id: "p664", title: "Nina", answer: "OSMOSIS", tags: ["meta:optics-lab"], url: "http://www.20000puzzles.com/puzzle/nina/"},

  // Machine room appears to be missing a metapuzzle URL
  { id: "r67", title: "Machine Room", answer: "AETHER BALLAST TANK", tags: ["meta", "meta:machine-room"], url: "http://www.20000puzzles.com/"},
  { id: "p668", title: "Imba", answer: "fundaymonday", tags: ["meta:machine-room"], url: "http://www.20000puzzles.com/puzzle/imba"},
  { id: "p653", title: "Beth", answer: "prince", tags: ["meta:machine-room"], url: "http://www.20000puzzles.com/puzzle/beth/"},
  { id: "p644", title: "Erraticism", answer: "IFEELBADFORYOU", tags: ["meta:machine-room"], url: "http://www.20000puzzles.com/puzzle/erraticism/"},
  { id: "p658", title: "Back on the Move", answer: "NENA", tags: ["meta:machine-room"], url: "http://www.20000puzzles.com/puzzle/back_on_the_move"},
  { id: "p645", title: "Loony Playhouse Actors", answer: "nonarygame", tags: ["meta:machine-room"], url: "http://www.20000puzzles.com/puzzle/loony_playhouse_actors/"},
  { id: "p660", title: "Nautilus's Duplicated Quest", answer: "sea to sky", tags: ["meta:machine-room"], url: "http://www.20000puzzles.com/puzzle/nautiluss_duplicated_quest"},
  { id: "p646", title: "Takeout Ordering", answer: "onthewall", tags: ["meta:machine-room"], url: "http://www.20000puzzles.com/puzzle/takeout_ordering/"},
  { id: "p659", title: "Nope!", answer: "OVER", tags: ["meta:machine-room"], url: "http://www.20000puzzles.com/puzzle/nope"},
  { id: "p655", title: "A Rare Teak", answer: "PRAWN", tags: ["meta:machine-room"], url: "http://www.20000puzzles.com/puzzle/a_rare_teak/"},

  // Events
  { id: "p648", title: "Write-It Build-It (Friday, 6:17pm, Lobdell)", answer: "kelpsmoothie", tags: ["event"], url: "http://www.20000puzzles.com/puzzle/write_it_build_it"},
  { id: "p649", title: "Blub Blub Pub Trivia (Friday, 11:17pm, Lobdell)", answer: "ROOT BEER DEAD MANS FLOAT", tags: ["event"], url: "http://www.20000puzzles.com/puzzle/blub_blub_pub_trivia"},
  { id: "p650", title: "Steamteam (Saturday, 10:17am, Lobdell)", answer: "bubbletea", tags: ["event","spaceteam"], url: "http://www.20000puzzles.com/puzzle/steamteam"},
  { id: "p651", title: "Sunken Treasure (Saturday, 1:17pm, Z-Center second-floor entrance to pool gallery)", answer: "aquatictonic", tags: ["event"], url: "http://www.20000puzzles.com/puzzle/sunken_treasure"},
  { id: "p652", title: "Charybdis Charades (Saturday, 4:17pm, Lobdell)", answer: "SHAKE", tags: ["event"], url: "http://www.20000puzzles.com/puzzle/charybdis_charades"},

];
