import type { GuessType } from "./lib/models/Guesses";
import type { HuntType } from "./lib/models/Hunts";
import type { PuzzleType } from "./lib/models/Puzzles";
import type { TagType } from "./lib/models/Tags";

export type FixtureHuntType = Pick<HuntType, "_id" | "name"> & {
  tags: Pick<TagType, "_id" | "name">[];
  puzzles: (Pick<
    PuzzleType,
    "_id" | "title" | "url" | "expectedAnswerCount" | "tags"
  > & {
    guesses: (Pick<GuessType, "_id" | "guess" | "state"> & {
      additionalNotes?: string;
    })[];
  })[];
};

const FixtureHunt: FixtureHuntType = {
  _id: "S5BBzdFRnKSDktDwd",
  name: "Mystery Hunt 2018",
  tags: [
    { _id: "QeJLufdCqv7rMSSbS", name: "group:anger" },
    { _id: "9RDaMHxkZSJFezo6r", name: "group:build" },
    { _id: "avbpSWSL5YX9CNHpu", name: "group:deploy" },
    { _id: "FhwKoPgXvJ9iZzkG9", name: "group:disgust" },
    { _id: "o5JdfTizW4tGwhRnP", name: "group:emotions" },
    { _id: "6pxb246CFTmdsJpow", name: "group:events" },
    { _id: "Gwghj9nJfCzJBTwhQ", name: "group:fear" },
    { _id: "kghTda4PPdJYfJMuK", name: "group:flee" },
    { _id: "nPbTi6DPvjAkot94n", name: "group:games-island" },
    { _id: "PWZZge8id26rPH8t9", name: "group:hacking-island" },
    { _id: "vLzFKQuzAZZeQuAEX", name: "group:joy" },
    { _id: "m2EPY5Ty7ZPrkLisH", name: "group:sadness" },
    { _id: "NwhNGo64jRs384HwN", name: "group:scout" },
    { _id: "27YauwyRpL6yMsCef", name: "is:meta" },
    { _id: "3GmSvYwYM5zy9f2F2", name: "is:metameta" },
    { _id: "6uEokZ47zxWYp82c2", name: "meta-for:anger" },
    { _id: "ZJ2ihL4gT6gkmRgRo", name: "meta-for:build" },
    { _id: "mtzStZ4mwNmjzsbs2", name: "meta-for:deploy" },
    { _id: "u8brYN3fD9gAbYPmu", name: "meta-for:disgust" },
    { _id: "pq7EbR5SnY3C2iRmQ", name: "meta-for:fear" },
    { _id: "NfPmxPpNBQKNR2Y7M", name: "meta-for:flee" },
    { _id: "5rMx6AkFJnTxxn9g3", name: "meta-for:games-island" },
    { _id: "824j638yaMPZgRwCG", name: "meta-for:hacking-island" },
    { _id: "GHpDh3wjchBTm2Rnm", name: "meta-for:joy" },
    { _id: "2Z4MpQrREfBrnwLie", name: "meta-for:sadness" },
    { _id: "pgMERSdKeowNn2xpd", name: "meta-for:scout" },
  ],
  puzzles: [
    {
      _id: "fXchzrh8X9EoSZu6k",
      title: "Yeah, but It Didn’t Work!",
      url: "https://puzzles.mit.edu/2018/full/puzzle/yeah_but_it_didnt_work.html",
      expectedAnswerCount: 1,
      tags: ["o5JdfTizW4tGwhRnP", "QeJLufdCqv7rMSSbS"],
      guesses: [
        { _id: "obeeKs3ZEkBe3ykeg", guess: "AD NAUSEAM", state: "correct" },
      ],
    },
    {
      _id: "sZx8hSuCQ3nijFmjo",
      title: "Warm and Fuzzy",
      url: "https://puzzles.mit.edu/2018/full/puzzle/warm_and_fuzzy.html",
      expectedAnswerCount: 1,
      tags: ["o5JdfTizW4tGwhRnP", "vLzFKQuzAZZeQuAEX"],
      guesses: [
        { _id: "au5tuqM3NEpbtKY6s", guess: "INSIGHT", state: "correct" },
      ],
    },
    {
      _id: "qxyZuhSiozLoXCrS7",
      title: "Clueless",
      url: "https://puzzles.mit.edu/2018/full/puzzle/clueless.html",
      expectedAnswerCount: 1,
      tags: ["o5JdfTizW4tGwhRnP", "FhwKoPgXvJ9iZzkG9"],
      guesses: [
        { _id: "vAAFQL6CQjjoFjBbo", guess: "KERNEL", state: "correct" },
      ],
    },
    {
      _id: "XwXLY2hNDRcmrEeLX",
      title: "In Memoriam",
      url: "https://puzzles.mit.edu/2018/full/puzzle/in_memoriam.html",
      expectedAnswerCount: 1,
      tags: ["o5JdfTizW4tGwhRnP", "m2EPY5Ty7ZPrkLisH"],
      guesses: [
        {
          _id: "idK6wxaWCHpDbczpE",
          guess: "ISLAND OF OPPORTUNITY",
          state: "correct",
        },
      ],
    },
    {
      _id: "jCcDsEQDmKpygLj5j",
      title: "Freak Out",
      url: "https://puzzles.mit.edu/2018/full/puzzle/freak_out.html",
      expectedAnswerCount: 1,
      tags: ["o5JdfTizW4tGwhRnP", "Gwghj9nJfCzJBTwhQ"],
      guesses: [
        { _id: "a8srA9gF3iqBxbffz", guess: "SOUNDS", state: "correct" },
      ],
    },
    {
      _id: "JFyWGwD5roECxYk3a",
      title: "Let’s Get Ready to Jumble",
      url: "https://puzzles.mit.edu/2018/full/puzzle/lets_get_ready_to_jumble.html",
      expectedAnswerCount: 1,
      tags: ["o5JdfTizW4tGwhRnP", "QeJLufdCqv7rMSSbS"],
      guesses: [
        {
          _id: "yHtJYeqdmGkgCCcCL",
          guess: "TAPE YOUR HEEL TURN",
          state: "intermediate",
          additionalNotes:
            "Please upload your file to https://upload.head-hunters.org/.",
        },
        { _id: "wBik5mReoQMAhS6aX", guess: "ERIC ANGLE", state: "correct" },
      ],
    },
    {
      _id: "TfZjwQ8Z4k2hmRhCq",
      title: "AKA",
      url: "https://puzzles.mit.edu/2018/full/puzzle/aka.html",
      expectedAnswerCount: 1,
      tags: ["o5JdfTizW4tGwhRnP", "FhwKoPgXvJ9iZzkG9"],
      guesses: [
        { _id: "rXwyD8WBML8zHqgMQ", guess: "STEP DADDY", state: "correct" },
      ],
    },
    {
      _id: "t3ELZpXBz3FaiLe2i",
      title: "Unfortunate Al",
      url: "https://puzzles.mit.edu/2018/full/puzzle/unfortunate_al.html",
      expectedAnswerCount: 1,
      tags: ["o5JdfTizW4tGwhRnP", "m2EPY5Ty7ZPrkLisH"],
      guesses: [
        {
          _id: "FxSxquTZ7F4qwDyLS",
          guess: "INCREDIBLY STUPID",
          state: "correct",
        },
      ],
    },
    {
      _id: "vQdQNMmuM3QkKT23u",
      title: "A Learning Path",
      url: "https://puzzles.mit.edu/2018/full/puzzle/a_learning_path.html",
      expectedAnswerCount: 1,
      tags: ["o5JdfTizW4tGwhRnP", "Gwghj9nJfCzJBTwhQ", "FhwKoPgXvJ9iZzkG9"],
      guesses: [
        { _id: "QE46w8EKSMAEND6qn", guess: "EXCEPT", state: "correct" },
      ],
    },
    {
      _id: "eQpPRTrHJdYrGStFY",
      title: "Cross Words",
      url: "https://puzzles.mit.edu/2018/full/puzzle/cross_words.html",
      expectedAnswerCount: 1,
      tags: ["o5JdfTizW4tGwhRnP", "QeJLufdCqv7rMSSbS"],
      guesses: [
        { _id: "juFuFGnxwEHjLGfJq", guess: "ARGUE OVER", state: "correct" },
      ],
    },
    {
      _id: "KhjQ6DPp5Gwq6juuE",
      title: "We Are All Afraid to Die",
      url: "https://puzzles.mit.edu/2018/full/puzzle/we_are_all_afraid_to_die.html",
      expectedAnswerCount: 1,
      tags: ["o5JdfTizW4tGwhRnP", "Gwghj9nJfCzJBTwhQ"],
      guesses: [
        {
          _id: "NP82kJ8cEwf5uwW49",
          guess: "MEDICAL EMERGENCY",
          state: "correct",
        },
      ],
    },
    {
      _id: "yZKtXk5oLJMGqwP6E",
      title: "Temperance",
      url: "https://puzzles.mit.edu/2018/full/puzzle/temperance.html",
      expectedAnswerCount: 1,
      tags: ["o5JdfTizW4tGwhRnP", "QeJLufdCqv7rMSSbS", "FhwKoPgXvJ9iZzkG9"],
      guesses: [
        { _id: "9o3GKh9TPrnLDcoHu", guess: "BONE GRAFT", state: "correct" },
      ],
    },
    {
      _id: "JXLx7325fbEZmZnQk",
      title: "Word Search",
      url: "https://puzzles.mit.edu/2018/full/puzzle/word_search.html",
      expectedAnswerCount: 1,
      tags: ["o5JdfTizW4tGwhRnP", "Gwghj9nJfCzJBTwhQ", "m2EPY5Ty7ZPrkLisH"],
      guesses: [
        { _id: "FR2JKRhL3FKTp6rvx", guess: "GONORRHEA", state: "incorrect" },
        { _id: "cybpaQuntAoWWx5TS", guess: "NECESSARY", state: "correct" },
      ],
    },
    {
      _id: "hfLuHwt8iHpRRHABC",
      title: "Just Keep Swiping",
      url: "https://puzzles.mit.edu/2018/full/puzzle/just_keep_swiping.html",
      expectedAnswerCount: 1,
      tags: ["o5JdfTizW4tGwhRnP", "FhwKoPgXvJ9iZzkG9"],
      guesses: [
        { _id: "SEkwpkkTzjxQDdN7r", guess: "ROUGH DATE", state: "correct" },
      ],
    },
    {
      _id: "yL2otu4mhRC4HGw3d",
      title: "Caged",
      url: "https://puzzles.mit.edu/2018/full/puzzle/caged.html",
      expectedAnswerCount: 1,
      tags: ["o5JdfTizW4tGwhRnP", "vLzFKQuzAZZeQuAEX", "m2EPY5Ty7ZPrkLisH"],
      guesses: [
        { _id: "kCpXszsTR6dgLJkiB", guess: "HORSES", state: "correct" },
      ],
    },
    {
      _id: "nLgC7z8cRcnovBy7Y",
      title: "Minority Report",
      url: "https://puzzles.mit.edu/2018/full/puzzle/minority_report.html",
      expectedAnswerCount: 1,
      tags: ["o5JdfTizW4tGwhRnP", "FhwKoPgXvJ9iZzkG9"],
      guesses: [
        { _id: "Rdh3k7WaJWgQFHc6W", guess: "FILM COUNCILS", state: "correct" },
      ],
    },
    {
      _id: "zErakd8ndNvS3Aioz",
      title: "Asteroids",
      url: "https://puzzles.mit.edu/2018/full/puzzle/asteroids.html",
      expectedAnswerCount: 1,
      tags: ["o5JdfTizW4tGwhRnP", "QeJLufdCqv7rMSSbS"],
      guesses: [
        { _id: "bxP8TBGcaGdjQQ4QD", guess: "LASER BEAM", state: "correct" },
      ],
    },
    {
      _id: "Qtqs9hD6m7MYt8iam",
      title: "Good Fences Make Sad and Disgusted Neighbors",
      url: "https://puzzles.mit.edu/2018/full/puzzle/good_fences_make_sad_and_disgusted_neighbors.html",
      expectedAnswerCount: 1,
      tags: ["o5JdfTizW4tGwhRnP", "m2EPY5Ty7ZPrkLisH", "FhwKoPgXvJ9iZzkG9"],
      guesses: [
        { _id: "XRdcHMnF3n8bNEgME", guess: "HOW GREAT", state: "correct" },
      ],
    },
    {
      _id: "u7zPtrDTX3wSvfbTu",
      title: "Face Your Fears",
      url: "https://puzzles.mit.edu/2018/full/puzzle/face_your_fears.html",
      expectedAnswerCount: 1,
      tags: ["o5JdfTizW4tGwhRnP", "Gwghj9nJfCzJBTwhQ"],
      guesses: [
        { _id: "PMmwPMJvEk8aiJcy5", guess: "REGARDLESS", state: "correct" },
      ],
    },
    {
      _id: "QSCB9ZGawfZQizqmW",
      title: "Scattered and Absurd",
      url: "https://puzzles.mit.edu/2018/full/puzzle/scattered_and_absurd.html",
      expectedAnswerCount: 1,
      tags: ["o5JdfTizW4tGwhRnP", "QeJLufdCqv7rMSSbS", "m2EPY5Ty7ZPrkLisH"],
      guesses: [
        { _id: "Q9wxAbr8e8wx5PkP8", guess: "SUPERIORS", state: "correct" },
      ],
    },
    {
      _id: "Samtmy5LdNLcxWqHP",
      title: "Cooking a Recipe",
      url: "https://puzzles.mit.edu/2018/full/puzzle/cooking_a_recipe.html",
      expectedAnswerCount: 1,
      tags: ["o5JdfTizW4tGwhRnP", "vLzFKQuzAZZeQuAEX", "FhwKoPgXvJ9iZzkG9"],
      guesses: [
        { _id: "wpFmBSDdJe6pvXDfq", guess: "REAL FOOD", state: "correct" },
      ],
    },
    {
      _id: "yEZdXSXS4XcybsvXp",
      title: "Roadside America",
      url: "https://puzzles.mit.edu/2018/full/puzzle/roadside_america.html",
      expectedAnswerCount: 1,
      tags: ["o5JdfTizW4tGwhRnP", "QeJLufdCqv7rMSSbS", "Gwghj9nJfCzJBTwhQ"],
      guesses: [
        { _id: "TYZK74nDK7pBFQg6L", guess: "EXCURSION", state: "correct" },
      ],
    },
    {
      _id: "6mnHLb6HYp3bsahLn",
      title: "Crossed Paths",
      url: "https://puzzles.mit.edu/2018/full/puzzle/crossed_paths.html",
      expectedAnswerCount: 1,
      tags: ["o5JdfTizW4tGwhRnP", "vLzFKQuzAZZeQuAEX"],
      guesses: [
        { _id: "XL2e3vivnqW4cF9Mv", guess: "RITUAL", state: "correct" },
      ],
    },
    {
      _id: "bH3DmnKcabcvuTp9W",
      title: "On the A Line",
      url: "https://puzzles.mit.edu/2018/full/puzzle/on_the_a_line.html",
      expectedAnswerCount: 1,
      tags: ["o5JdfTizW4tGwhRnP", "FhwKoPgXvJ9iZzkG9"],
      guesses: [{ _id: "EnnQ8rctamQCkgTua", guess: "STYLE", state: "correct" }],
    },
    {
      _id: "WCpKXdtJtLiqvPyT4",
      title: "What’s In a Name?",
      url: "https://puzzles.mit.edu/2018/full/puzzle/whats_in_a_name.html",
      expectedAnswerCount: 1,
      tags: ["o5JdfTizW4tGwhRnP", "QeJLufdCqv7rMSSbS"],
      guesses: [
        { _id: "ibupxCGukcX6aMnC5", guess: "ELIZABETH", state: "correct" },
      ],
    },
    {
      _id: "epk4jZ8chxxpho44g",
      title: "Games Club",
      url: "https://puzzles.mit.edu/2018/full/puzzle/games_club.html",
      expectedAnswerCount: 1,
      tags: ["o5JdfTizW4tGwhRnP", "m2EPY5Ty7ZPrkLisH"],
      guesses: [
        { _id: "LLt8GWatdBrHuf7iL", guess: "PARTICIPATE", state: "correct" },
      ],
    },
    {
      _id: "uaMAnXEgj9SsvFZcv",
      title: "Birds of a Feather",
      url: "https://puzzles.mit.edu/2018/full/puzzle/birds_of_a_feather.html",
      expectedAnswerCount: 1,
      tags: ["o5JdfTizW4tGwhRnP", "vLzFKQuzAZZeQuAEX", "QeJLufdCqv7rMSSbS"],
      guesses: [
        { _id: "ofYdeS8khM2Dpr3eB", guess: "ASCENSION", state: "correct" },
      ],
    },
    {
      _id: "gpAcAiCGiKDAZTztf",
      title: "Nobody Likes Sad Songs",
      url: "https://puzzles.mit.edu/2018/full/puzzle/nobody_likes_sad_songs.html",
      expectedAnswerCount: 1,
      tags: ["o5JdfTizW4tGwhRnP", "m2EPY5Ty7ZPrkLisH"],
      guesses: [
        { _id: "fqnEPtJNgYAMQvpsN", guess: "VISION", state: "correct" },
      ],
    },
    {
      _id: "Li5ikreZpqY2s7HD3",
      title: "Irritating Places",
      url: "https://puzzles.mit.edu/2018/full/puzzle/irritating_places.html",
      expectedAnswerCount: 1,
      tags: ["o5JdfTizW4tGwhRnP", "QeJLufdCqv7rMSSbS"],
      guesses: [
        { _id: "paNCu7yxHdDBoW689", guess: "ASTRAKHAN", state: "correct" },
      ],
    },
    {
      _id: "8d7XPES3AvP2oWxX9",
      title: "What The...",
      url: "https://puzzles.mit.edu/2018/full/puzzle/what_the.html",
      expectedAnswerCount: 1,
      tags: ["o5JdfTizW4tGwhRnP", "vLzFKQuzAZZeQuAEX", "Gwghj9nJfCzJBTwhQ"],
      guesses: [
        { _id: "2yAYSNYxabrimjqEv", guess: "STRATEGY", state: "correct" },
      ],
    },
    {
      _id: "ymFLoyD9SKXGYjg9u",
      title: "Beast Workshop",
      url: "https://puzzles.mit.edu/2018/full/puzzle/beast_workshop.html",
      expectedAnswerCount: 1,
      tags: ["o5JdfTizW4tGwhRnP", "FhwKoPgXvJ9iZzkG9"],
      guesses: [
        { _id: "Hd9cHk2QjD7aeYPEa", guess: "NIGHTLY", state: "correct" },
      ],
    },
    {
      _id: "wwT2gwvpeGD3RBGEr",
      title: "That Time I Somehow Felt Incomplete",
      url: "https://puzzles.mit.edu/2018/full/puzzle/that_time_i_somehow_felt_incomplete.html",
      expectedAnswerCount: 1,
      tags: ["o5JdfTizW4tGwhRnP", "QeJLufdCqv7rMSSbS"],
      guesses: [
        { _id: "FyaSEos9TWKvbtd3H", guess: "EXAM GRADE", state: "correct" },
      ],
    },
    {
      _id: "BDviNTjeKSaFFRRRn",
      title: "Jeopardy!",
      url: "https://puzzles.mit.edu/2018/full/puzzle/jeopardy.html",
      expectedAnswerCount: 1,
      tags: ["o5JdfTizW4tGwhRnP", "Gwghj9nJfCzJBTwhQ"],
      guesses: [
        { _id: "HnS9opDNYRBhwBsR7", guess: "VOLUNTEER", state: "correct" },
      ],
    },
    {
      _id: "4Aoib4dvmmDApWPWH",
      title: "Chemistry Experimentation",
      url: "https://puzzles.mit.edu/2018/full/puzzle/chemistry_experimentation.html",
      expectedAnswerCount: 1,
      tags: ["o5JdfTizW4tGwhRnP", "QeJLufdCqv7rMSSbS"],
      guesses: [
        { _id: "JkddmqGnMAfHKG6uP", guess: "AMBER BEER", state: "correct" },
      ],
    },
    {
      _id: "Enve2KvnsSPnf3AZi",
      title: "Joy",
      url: "https://puzzles.mit.edu/2018/full/puzzle/joy.html",
      expectedAnswerCount: 1,
      tags: [
        "o5JdfTizW4tGwhRnP",
        "vLzFKQuzAZZeQuAEX",
        "GHpDh3wjchBTm2Rnm",
        "27YauwyRpL6yMsCef",
      ],
      guesses: [
        { _id: "mP8c9rvHTDR7DYYcw", guess: "BEAM UP", state: "correct" },
      ],
    },
    {
      _id: "tHgNPEYddvkvbc844",
      title: "Sadness",
      url: "https://puzzles.mit.edu/2018/full/puzzle/sadness.html",
      expectedAnswerCount: 1,
      tags: [
        "o5JdfTizW4tGwhRnP",
        "27YauwyRpL6yMsCef",
        "m2EPY5Ty7ZPrkLisH",
        "2Z4MpQrREfBrnwLie",
      ],
      guesses: [
        { _id: "6HasNYjRhHtAbms8H", guess: "TEAR DUCT", state: "correct" },
      ],
    },
    {
      _id: "KDWQCMWZGmR4YMyMC",
      title: "Fear",
      url: "https://puzzles.mit.edu/2018/full/puzzle/fear.html",
      expectedAnswerCount: 1,
      tags: [
        "o5JdfTizW4tGwhRnP",
        "27YauwyRpL6yMsCef",
        "Gwghj9nJfCzJBTwhQ",
        "pq7EbR5SnY3C2iRmQ",
      ],
      guesses: [
        { _id: "crwmPiQsMJcaiq59M", guess: "BOLDLY GO", state: "correct" },
      ],
    },
    {
      _id: "RMdhQr6XF4ysnmWAg",
      title: "Disgust",
      url: "https://puzzles.mit.edu/2018/full/puzzle/disgust.html",
      expectedAnswerCount: 1,
      tags: [
        "o5JdfTizW4tGwhRnP",
        "27YauwyRpL6yMsCef",
        "FhwKoPgXvJ9iZzkG9",
        "u8brYN3fD9gAbYPmu",
      ],
      guesses: [
        { _id: "HQPvyBHozBpkecewo", guess: "RAPPEL", state: "correct" },
      ],
    },
    {
      _id: "DsJRvwWk5h8pY7W4b",
      title: "Anger",
      url: "https://puzzles.mit.edu/2018/full/puzzle/anger.html",
      expectedAnswerCount: 1,
      tags: [
        "o5JdfTizW4tGwhRnP",
        "27YauwyRpL6yMsCef",
        "QeJLufdCqv7rMSSbS",
        "6uEokZ47zxWYp82c2",
      ],
      guesses: [
        {
          _id: "wehFKp7n7KySbsNZB",
          guess: "PICK A FIGHT WITH LOCK",
          state: "correct",
        },
      ],
    },
    {
      _id: "hLFyTgtPqgXqCpPEW",
      title: "Care and Feeding of Your Mystery Hunt Team (Fri, 7:00PM)",
      url: "https://puzzles.mit.edu/2018/full/puzzle/care_and_feeding_of_your_mystery_hunt_team.html",
      expectedAnswerCount: 1,
      tags: ["6pxb246CFTmdsJpow"],
      guesses: [
        { _id: "x9miKALfxKvu8oKuW", guess: "CLEAN UP", state: "correct" },
      ],
    },
    {
      _id: "QvW6PoXpm6woKTSxK",
      title:
        "Effective Resource Management in High Stress Situations (Fri, 10:00PM)",
      url: "https://puzzles.mit.edu/2018/full/puzzle/effective_resource_management_in_high_stress_situations.html",
      expectedAnswerCount: 1,
      tags: ["6pxb246CFTmdsJpow"],
      guesses: [
        { _id: "BcftzWPa3KQqoWarv", guess: "NICK OF TIME", state: "correct" },
      ],
    },
    {
      _id: "hWP2aPzQSyeK9zbqR",
      title: "Covering Your Ass With Caution Tape (Sat, 9:00AM)",
      url: "https://puzzles.mit.edu/2018/full/puzzle/covering_your_ass_with_caution_tape.html",
      expectedAnswerCount: 1,
      tags: ["6pxb246CFTmdsJpow"],
      guesses: [
        {
          _id: "Jr9B3k2kD3i72o7zz",
          guess: "MEASURE TWICE CUT ONCE",
          state: "correct",
        },
      ],
    },
    {
      _id: "KForsXaMQutWujXS3",
      title: "Stretching and Calisthenics (Sat, 2:00PM)",
      url: "https://puzzles.mit.edu/2018/full/puzzle/stretching_and_calisthenics.html",
      expectedAnswerCount: 1,
      tags: ["6pxb246CFTmdsJpow"],
      guesses: [
        {
          _id: "fh978nKrtmiCfYDJg",
          guess: "ROOT BEER FLOAT",
          state: "correct",
        },
      ],
    },
    {
      _id: "rpgGvAcifwGHBizii",
      title: "Communication and Cooperation for Proper Teamwork (Sat, 7:00PM)",
      url: "https://puzzles.mit.edu/2018/full/puzzle/communication_and_cooperation_for_proper_teamwork.html",
      expectedAnswerCount: 1,
      tags: ["6pxb246CFTmdsJpow"],
      guesses: [
        {
          _id: "3bQYzutT3zDiXLKzN",
          guess: "KEEP IT TOGETHER",
          state: "correct",
        },
      ],
    },
    {
      _id: "eoscDr46t5Pjuk8C3",
      title: "This Year’s Hardest Crossword",
      url: "https://puzzles.mit.edu/2018/full/puzzle/this_years_hardest_crossword.html",
      expectedAnswerCount: 1,
      tags: ["nPbTi6DPvjAkot94n"],
      guesses: [
        {
          _id: "kfeD2uWtGfCns5uoB",
          guess: "NOW SOLVE TODAY'S LISTENER",
          state: "intermediate",
          additionalNotes:
            "The Listener can be found at http://www.listenercrossword.com/Solutions/S2018/Notes_4485.html",
        },
        { _id: "ukBCpRvEYNtmADDgX", guess: "WHOOPEE", state: "correct" },
      ],
    },
    {
      _id: "p3RTZLXXt2n47kAJX",
      title: "Flattery Will Get You Nowhere",
      url: "https://puzzles.mit.edu/2018/full/puzzle/flattery_will_get_you_nowhere.html",
      expectedAnswerCount: 1,
      tags: ["nPbTi6DPvjAkot94n"],
      guesses: [
        { _id: "JhcRxkskC8m5JbKyn", guess: "PORTMANTEAU", state: "correct" },
      ],
    },
    {
      _id: "vgjpuSksmkd4txzEL",
      title: "Sports Radio",
      url: "https://puzzles.mit.edu/2018/full/puzzle/sports_radio.html",
      expectedAnswerCount: 1,
      tags: ["nPbTi6DPvjAkot94n"],
      guesses: [
        {
          _id: "SxZ7jcaLwRJ65iooc",
          guess: "ULTIMATE FRISBEE",
          state: "correct",
        },
      ],
    },
    {
      _id: "D8koE3yHo4zDPsqrK",
      title: "Tournament Organization",
      url: "https://puzzles.mit.edu/2018/full/puzzle/tournament_organization.html",
      expectedAnswerCount: 1,
      tags: ["nPbTi6DPvjAkot94n"],
      guesses: [
        { _id: "ty6XhdxY5dypoCW7m", guess: "SPOT THE BALL", state: "correct" },
      ],
    },
    {
      _id: "bdYQp7iQXCmHnXzeR",
      title: "All the Right Angles",
      url: "https://puzzles.mit.edu/2018/full/puzzle/all_the_right_angles.html",
      expectedAnswerCount: 1,
      tags: ["nPbTi6DPvjAkot94n"],
      guesses: [
        { _id: "7RcPgs2f98SZvbD6s", guess: "POCKET MONEY", state: "correct" },
      ],
    },
    {
      _id: "oiYBG7codxqCnaMg8",
      title: "Cartography",
      url: "https://puzzles.mit.edu/2018/full/puzzle/cartography.html",
      expectedAnswerCount: 1,
      tags: ["nPbTi6DPvjAkot94n"],
      guesses: [
        { _id: "c4ZXuzP3R8nWr3cPC", guess: "PINNACLES", state: "correct" },
      ],
    },
    {
      _id: "n68eqTvZxaY7XRYZh",
      title: "Pestered",
      url: "https://puzzles.mit.edu/2018/full/puzzle/pestered.html",
      expectedAnswerCount: 1,
      tags: ["nPbTi6DPvjAkot94n"],
      guesses: [
        { _id: "gi2waG948jjsdpwcW", guess: "MASTER AT ARMS", state: "correct" },
      ],
    },
    {
      _id: "E8RMTS7f6ku9i9kDD",
      title: "A Tribute: 2010-2017",
      url: "https://puzzles.mit.edu/2018/full/puzzle/a_tribute_2010_2017.html",
      expectedAnswerCount: 1,
      tags: ["nPbTi6DPvjAkot94n"],
      guesses: [
        { _id: "5cA9nqpdiKgPfShHj", guess: "MEMORIAL", state: "correct" },
      ],
    },
    {
      _id: "s4q8ruLiiN4fR3RCb",
      title: "GRATIA PLENA",
      url: "https://puzzles.mit.edu/2018/full/puzzle/gratia_plena.html",
      expectedAnswerCount: 1,
      tags: ["nPbTi6DPvjAkot94n"],
      guesses: [
        { _id: "JQu85Z4CtLYeQwd6n", guess: "CODEX RUNICUS", state: "correct" },
      ],
    },
    {
      _id: "Nt7MzPg9FmHB6dJso",
      title: "Thanks",
      url: "https://puzzles.mit.edu/2018/full/puzzle/thanks.html",
      expectedAnswerCount: 1,
      tags: ["nPbTi6DPvjAkot94n"],
      guesses: [
        { _id: "EsdxjHKgphrfnTMfv", guess: "PANDORA", state: "correct" },
      ],
    },
    {
      _id: "eAS2328WXAnnREYdv",
      title: "Walk Across Some Dungeons 2",
      url: "https://puzzles.mit.edu/2018/full/puzzle/walk_across_some_dungeons_2.html",
      expectedAnswerCount: 1,
      tags: ["nPbTi6DPvjAkot94n"],
      guesses: [
        {
          _id: "yTFGdwKzP7oWALaTW",
          guess: "KEYBOARD PLAYER",
          state: "correct",
        },
      ],
    },
    {
      _id: "MZH8Wcaui8Ahr42Ko",
      title: "Special Delivery",
      url: "https://puzzles.mit.edu/2018/full/puzzle/special_delivery.html",
      expectedAnswerCount: 1,
      tags: ["nPbTi6DPvjAkot94n"],
      guesses: [
        {
          _id: "v8fxXBfvn3HdXpNrZ",
          guess: "WE WANT A MOCKTAIL",
          state: "intermediate",
          additionalNotes:
            "Please bring your beverage to 66-100, and be prepared to tell them your team and the instruction that brought you here.",
        },
        { _id: "fN4zRHuk2xJkq6Wcr", guess: "DIRTY MARTINI", state: "correct" },
      ],
    },
    {
      _id: "oL8CLFBzdt8DKQjCb",
      title: "Do You Want A",
      url: "https://puzzles.mit.edu/2018/full/puzzle/do_you_want_a.html",
      expectedAnswerCount: 1,
      tags: ["nPbTi6DPvjAkot94n"],
      guesses: [
        { _id: "CeKrsGCBmufdbtSKK", guess: "ONSIGHT", state: "correct" },
      ],
    },
    {
      _id: "Yh4zw7oitEPyvZumB",
      title: "Shift",
      url: "https://puzzles.mit.edu/2018/full/puzzle/shift.html",
      expectedAnswerCount: 1,
      tags: ["nPbTi6DPvjAkot94n"],
      guesses: [
        { _id: "EBkZFnKcDe64BqiMT", guess: "SLEEPER AGENT", state: "correct" },
      ],
    },
    {
      _id: "hiMpJHfWjotCGb9NT",
      title: "America’s Best Friends",
      url: "https://puzzles.mit.edu/2018/full/puzzle/americas_best_friends.html",
      expectedAnswerCount: 1,
      tags: ["nPbTi6DPvjAkot94n"],
      guesses: [
        {
          _id: "5bYkNpXBC2mAdZBDC",
          guess: "JONATHAN EDWARDS",
          state: "pending",
        },
      ],
    },
    {
      _id: "ovngS9XCjtT2DK5kM",
      title: "Little Passages",
      url: "https://puzzles.mit.edu/2018/full/puzzle/little_passages.html",
      expectedAnswerCount: 1,
      tags: ["nPbTi6DPvjAkot94n"],
      guesses: [],
    },
    {
      _id: "Wmq2gDhZwPhBaWgM3",
      title: "Middle of the Road",
      url: "https://puzzles.mit.edu/2018/full/puzzle/middle_of_the_road.html",
      expectedAnswerCount: 1,
      tags: ["nPbTi6DPvjAkot94n"],
      guesses: [],
    },
    {
      _id: "MaLLbExKyDdyrYLSS",
      title: "Death From Aslant",
      url: "https://puzzles.mit.edu/2018/full/puzzle/death_from_aslant.html",
      expectedAnswerCount: 1,
      tags: ["nPbTi6DPvjAkot94n"],
      guesses: [],
    },
    {
      _id: "NeMxJZKPGqN7CcmcN",
      title: "The Desert",
      url: "https://puzzles.mit.edu/2018/full/puzzle/the_desert.html",
      expectedAnswerCount: 1,
      tags: ["nPbTi6DPvjAkot94n", "27YauwyRpL6yMsCef", "5rMx6AkFJnTxxn9g3"],
      guesses: [
        {
          _id: "DPomSLQiQ2SzYfy9X",
          guess: "INTERCOASTAL EMPIRE",
          state: "correct",
        },
      ],
    },
    {
      _id: "3zTi6pDY9mHJSbLoS",
      title: "The Robber",
      url: "https://puzzles.mit.edu/2018/full/puzzle/the_robber.html",
      expectedAnswerCount: 1,
      tags: ["nPbTi6DPvjAkot94n", "27YauwyRpL6yMsCef", "5rMx6AkFJnTxxn9g3"],
      guesses: [],
    },
    {
      _id: "EvCuubJ4T5mrxtdQ3",
      title: "No Context",
      url: "https://puzzles.mit.edu/2018/full/puzzle/no_context.html",
      expectedAnswerCount: 1,
      tags: ["PWZZge8id26rPH8t9", "NwhNGo64jRs384HwN"],
      guesses: [
        { _id: "GwWpEqGMiMLAa8SvP", guess: "CHECKPOINT", state: "correct" },
      ],
    },
    {
      _id: "F2TeHBmuXXCjDY9bz",
      title: "The Lurking Horror II: The Lurkening",
      url: "https://puzzles.mit.edu/2018/full/puzzle/the_lurking_horror_ii_the_lurkening.html",
      expectedAnswerCount: 1,
      tags: ["PWZZge8id26rPH8t9", "NwhNGo64jRs384HwN"],
      guesses: [
        { _id: "QuvxE7AtMTptTSzLJ", guess: "ADVENTURE", state: "correct" },
      ],
    },
    {
      _id: "tDWaNvNBMwWLhzNsi",
      title: "Bark Ode",
      url: "https://puzzles.mit.edu/2018/full/puzzle/bark_ode.html",
      expectedAnswerCount: 1,
      tags: ["PWZZge8id26rPH8t9", "NwhNGo64jRs384HwN"],
      guesses: [
        { _id: "P6xLHMw8supFAxNhQ", guess: "TENDINOPATHIES", state: "correct" },
      ],
    },
    {
      _id: "shKWQ5NLnR8Noz53m",
      title: "Voter Fraud",
      url: "https://puzzles.mit.edu/2018/full/puzzle/voter_fraud.html",
      expectedAnswerCount: 1,
      tags: ["PWZZge8id26rPH8t9", "NwhNGo64jRs384HwN"],
      guesses: [
        { _id: "kSkLNE6DRYaD5SoR2", guess: "SKYSCRAPER", state: "correct" },
      ],
    },
    {
      _id: "88N2A4ek7A4jfnL7i",
      title: "The 10,000 Puzzle Tesseract",
      url: "https://puzzles.mit.edu/2018/full/puzzle/the_10000_puzzle_tesseract.html",
      expectedAnswerCount: 1,
      tags: ["PWZZge8id26rPH8t9", "NwhNGo64jRs384HwN"],
      guesses: [
        { _id: "RTwGKJqAtm6xghKvf", guess: "PERSONNEL", state: "correct" },
      ],
    },
    {
      _id: "vTfpYRaC2bg8iiB4u",
      title: "Worldwide Contacts",
      url: "https://puzzles.mit.edu/2018/full/puzzle/worldwide_contacts.html",
      expectedAnswerCount: 1,
      tags: ["PWZZge8id26rPH8t9", "NwhNGo64jRs384HwN"],
      guesses: [
        { _id: "3gTZKQpnTTwZa2b2c", guess: "INTERNATIONAL", state: "correct" },
      ],
    },
    {
      _id: "4B5umRZySigiXGY7t",
      title: "Texts From Mom",
      url: "https://puzzles.mit.edu/2018/full/puzzle/texts_from_mom.html",
      expectedAnswerCount: 1,
      tags: ["PWZZge8id26rPH8t9", "NwhNGo64jRs384HwN"],
      guesses: [
        { _id: "96G2tGePMBPFpiLT9", guess: "EXTEND", state: "correct" },
      ],
    },
    {
      _id: "HpP7JMrgaZvsiGKGp",
      title: "Murder at the Asylum",
      url: "https://puzzles.mit.edu/2018/full/puzzle/murder_at_the_asylum.html",
      expectedAnswerCount: 1,
      tags: ["PWZZge8id26rPH8t9", "NwhNGo64jRs384HwN"],
      guesses: [],
    },
    {
      _id: "YxhGFEJn9e3s94e9X",
      title: "Scout",
      url: "https://puzzles.mit.edu/2018/full/puzzle/scout.html",
      expectedAnswerCount: 1,
      tags: [
        "PWZZge8id26rPH8t9",
        "NwhNGo64jRs384HwN",
        "27YauwyRpL6yMsCef",
        "pgMERSdKeowNn2xpd",
        "kghTda4PPdJYfJMuK",
      ],
      guesses: [
        { _id: "ZnbzjovGdQA7sd67d", guess: "EXOSKELETON", state: "correct" },
      ],
    },
    {
      _id: "h2qPzvLuG2HuLCvWj",
      title: "Is There a Draft in Here?",
      url: "https://puzzles.mit.edu/2018/full/puzzle/is_there_a_draft_in_here.html",
      expectedAnswerCount: 1,
      tags: ["PWZZge8id26rPH8t9", "9RDaMHxkZSJFezo6r"],
      guesses: [
        { _id: "BE9sDXDqE6GuBYAxK", guess: "DRUNK ENOUGH", state: "correct" },
      ],
    },
    {
      _id: "BtWbqspfjow4uDpJi",
      title: "Marked Deck",
      url: "https://puzzles.mit.edu/2018/full/puzzle/marked_deck.html",
      expectedAnswerCount: 1,
      tags: ["PWZZge8id26rPH8t9", "9RDaMHxkZSJFezo6r"],
      guesses: [
        { _id: "MsqvutBm9kRWyyb9r", guess: "ROLLIN HAND", state: "correct" },
      ],
    },
    {
      _id: "jptsWtYmiodvxRFkB",
      title: "Model Kit",
      url: "https://puzzles.mit.edu/2018/full/puzzle/model_kit.html",
      expectedAnswerCount: 1,
      tags: ["PWZZge8id26rPH8t9", "9RDaMHxkZSJFezo6r"],
      guesses: [
        {
          _id: "BaaJYkCKACZawCkHX",
          guess: "CHEMISTRY SAVVY",
          state: "correct",
        },
      ],
    },
    {
      _id: "7nFkhb84xhx5iKxpm",
      title: "Arts and Crafts",
      url: "https://puzzles.mit.edu/2018/full/puzzle/arts_and_crafts.html",
      expectedAnswerCount: 1,
      tags: ["PWZZge8id26rPH8t9", "9RDaMHxkZSJFezo6r"],
      guesses: [
        {
          _id: "zQf7his5HcxmesfC6",
          guess: "DON'T BRUSH US OFF",
          state: "intermediate",
          additionalNotes:
            "Please come to 66-110 to pick up your item. Make sure to knock, and don’t come in until we let you in. Be prepared to say what team you’re with and the request that you submitted.",
        },
        {
          _id: "eaWNnnySz8kqDwcXu",
          guess: "MAKE A TIFO AND HOIST FOR HQ",
          state: "intermediate",
          additionalNotes:
            "Please upload your file to https://upload.head-hunters.org/.",
        },
        {
          _id: "jtTXcz8QXJfJYvzNx",
          guess: "CONFINED AQUIFER",
          state: "correct",
        },
      ],
    },
    {
      _id: "RxoCqBP6wQyDkT8NQ",
      title: "Blocked Lines",
      url: "https://puzzles.mit.edu/2018/full/puzzle/blocked_lines.html",
      expectedAnswerCount: 1,
      tags: ["PWZZge8id26rPH8t9", "9RDaMHxkZSJFezo6r"],
      guesses: [
        {
          _id: "tcTAgnRefAKGtWBGC",
          guess: "SQUARE POINTS",
          state: "intermediate",
          additionalNotes:
            "Please come to 66-110 to pick up your item. Make sure to knock, and don’t come in until we let you in. Be prepared to say what team you’re with and the request that you submitted.",
        },
        { _id: "9KtYfxo7dG2fNkEdy", guess: "THREE POUNDER", state: "correct" },
      ],
    },
    {
      _id: "oKngMGGxyjRhDhAEh",
      title: "Fowlty Towers",
      url: "https://puzzles.mit.edu/2018/full/puzzle/fowlty_towers.html",
      expectedAnswerCount: 1,
      tags: ["PWZZge8id26rPH8t9", "9RDaMHxkZSJFezo6r"],
      guesses: [],
    },
    {
      _id: "ZGenDuRpbWa3vPLNH",
      title: "Don’t Look",
      url: "https://puzzles.mit.edu/2018/full/puzzle/dont_look.html",
      expectedAnswerCount: 1,
      tags: ["PWZZge8id26rPH8t9", "9RDaMHxkZSJFezo6r"],
      guesses: [],
    },
    {
      _id: "2sSWptrSFs6wCCjAd",
      title: "Wolf in the Fold",
      url: "https://puzzles.mit.edu/2018/full/puzzle/wolf_in_the_fold.html",
      expectedAnswerCount: 1,
      tags: ["PWZZge8id26rPH8t9", "9RDaMHxkZSJFezo6r"],
      guesses: [],
    },
    {
      _id: "XcCSfJKhLQMBYYr3s",
      title: "Build",
      url: "https://puzzles.mit.edu/2018/full/puzzle/build.html",
      expectedAnswerCount: 1,
      tags: [
        "PWZZge8id26rPH8t9",
        "9RDaMHxkZSJFezo6r",
        "27YauwyRpL6yMsCef",
        "ZJ2ihL4gT6gkmRgRo",
        "kghTda4PPdJYfJMuK",
      ],
      guesses: [
        { _id: "TWfjQ68Y6Fa2ZgSSm", guess: "BIOFUEL TORCH", state: "correct" },
      ],
    },
    {
      _id: "ZufEumovmctRSnyFf",
      title: "Scouting Challenge",
      url: "https://puzzles.mit.edu/2018/full/puzzle/scouting_challenge.html",
      expectedAnswerCount: 1,
      tags: ["PWZZge8id26rPH8t9"],
      guesses: [
        { _id: "6cb5p87zDZsQrFJL8", guess: "TRUST NO ONE", state: "correct" },
      ],
    },
    {
      _id: "CAgbuza4av8WgjofN",
      title: "Building Challenge",
      url: "https://puzzles.mit.edu/2018/full/puzzle/building_challenge.html",
      expectedAnswerCount: 1,
      tags: ["PWZZge8id26rPH8t9"],
      guesses: [
        {
          _id: "d8ArsjzFPHZ5DR5MJ",
          guess: "REDUCE AND RECYCLE",
          state: "correct",
        },
      ],
    },
    {
      _id: "GrTLWHPQaGiRWf983",
      title: "A Pub Crawl",
      url: "https://puzzles.mit.edu/2018/full/puzzle/a_pub_crawl.html",
      expectedAnswerCount: 1,
      tags: ["PWZZge8id26rPH8t9", "avbpSWSL5YX9CNHpu"],
      guesses: [
        { _id: "mAyrKK8iBSgt7xbYi", guess: "SOLERA", state: "correct" },
      ],
    },
    {
      _id: "2YwZtuNXQW8j8P7qr",
      title: "Executive Relationship Commandments",
      url: "https://puzzles.mit.edu/2018/full/puzzle/executive_relationship_commandments.html",
      expectedAnswerCount: 1,
      tags: ["PWZZge8id26rPH8t9", "avbpSWSL5YX9CNHpu"],
      guesses: [
        { _id: "545E7sSZxxd7DL9q5", guess: "PENPAL", state: "correct" },
      ],
    },
    {
      _id: "naXGFBwfucE6WNAjC",
      title: "Zelma & Frank",
      url: "https://puzzles.mit.edu/2018/full/puzzle/zelma_frank.html",
      expectedAnswerCount: 1,
      tags: ["PWZZge8id26rPH8t9", "avbpSWSL5YX9CNHpu"],
      guesses: [
        { _id: "i5gdoj74veJjbZr9g", guess: "HIKE UP", state: "correct" },
      ],
    },
    {
      _id: "iexwvYYYPAqZJi2oE",
      title: "Ode to the Greeks",
      url: "https://puzzles.mit.edu/2018/full/puzzle/ode_to_the_greeks.html",
      expectedAnswerCount: 1,
      tags: ["PWZZge8id26rPH8t9", "avbpSWSL5YX9CNHpu"],
      guesses: [
        { _id: "ZBTLBdsBTmkxCe76w", guess: "NEBULA", state: "correct" },
      ],
    },
    {
      _id: "ZTzrQsQePCg2mDtFj",
      title: "Studies in Two-Factor Authentication",
      url: "https://puzzles.mit.edu/2018/full/puzzle/studies_in_two_factor_authentication.html",
      expectedAnswerCount: 1,
      tags: ["PWZZge8id26rPH8t9", "avbpSWSL5YX9CNHpu"],
      guesses: [
        { _id: "X8qFFsfebNxxh5Kmr", guess: "BOTNET", state: "correct" },
      ],
    },
    {
      _id: "L2iQyYMkqFsmYqEKr",
      title: "L is for Library",
      url: "https://puzzles.mit.edu/2018/full/puzzle/l_is_for_library.html",
      expectedAnswerCount: 1,
      tags: ["PWZZge8id26rPH8t9", "avbpSWSL5YX9CNHpu"],
      guesses: [
        { _id: "tDb2p2nvoMEurcTwW", guess: "OCELOT", state: "correct" },
      ],
    },
    {
      _id: "uuTSi4WYwJmDroW5A",
      title: "Deploy",
      url: "https://puzzles.mit.edu/2018/full/puzzle/deploy.html",
      expectedAnswerCount: 1,
      tags: [
        "PWZZge8id26rPH8t9",
        "avbpSWSL5YX9CNHpu",
        "27YauwyRpL6yMsCef",
        "mtzStZ4mwNmjzsbs2",
        "kghTda4PPdJYfJMuK",
      ],
      guesses: [
        { _id: "6CFPPdcJfgRuxoR8K", guess: "BACKUP PLAN", state: "correct" },
      ],
    },
    {
      _id: "brhxu8L3rmY5px3FS",
      title: "Deployment Challenge",
      url: "https://puzzles.mit.edu/2018/full/puzzle/deployment_challenge.html",
      expectedAnswerCount: 1,
      tags: ["PWZZge8id26rPH8t9"],
      guesses: [
        { _id: "uFyDyi9LhddBxiRht", guess: "JUST IN CASE", state: "correct" },
      ],
    },
    {
      _id: "ufre63FZ45F4CQ9hg",
      title: "Flee",
      url: "https://puzzles.mit.edu/2018/full/puzzle/flee.html",
      expectedAnswerCount: 1,
      tags: [
        "PWZZge8id26rPH8t9",
        "3GmSvYwYM5zy9f2F2",
        "kghTda4PPdJYfJMuK",
        "824j638yaMPZgRwCG",
        "NfPmxPpNBQKNR2Y7M",
      ],
      guesses: [],
    },
  ],
};

export const FixtureHunt2: FixtureHuntType = {
  _id: "aaaaaaaaaaaaaaaaa",
  name: "Group-By Example",
  tags: [
    { _id: "arChartYourCourse", name: "artifact:Chart Your Course" },
    { _id: "arCryptozooLogist", name: "artifact:Cryptozoologist" },
    { _id: "arLetHerCookbooka", name: "artifact:Let Her Cookbook" },
    { _id: "arMixedMessaginga", name: "artifact:Mixed Messaging" },
    { _id: "arMonsterMashaaaa", name: "artifact:Monster Mash" },
    { _id: "arNameThatTuneaaa", name: "artifact:Name That Tune" },
    { _id: "arTheLabyrinthaaa", name: "artifact:The Labyrinth" },
    { _id: "arTownofTerroraaa", name: "artifact:Town of Terror" },
    { _id: "diKingdomofthePuz", name: "dimension:Kingdom of the Puzzmon" },
    { _id: "iscapstoneaaaaaaa", name: "is:capstone" },
    { _id: "ismetametaaaaaaaa", name: "is:metameta" },
    { _id: "isrunaroundaaaaaa", name: "is:runaround" },
    { _id: "mfarChartYourCour", name: "meta-for:artifact:Chart Your Course" },
    { _id: "mfarConnecttheCLa", name: "meta-for:artifact:Connect the Clans" },
    { _id: "mfarCryptozooLogi", name: "meta-for:artifact:Cryptozoologist" },
    { _id: "mfarLetHerCookboo", name: "meta-for:artifact:Let Her Cookbook" },
    { _id: "mfarMixedMessagin", name: "meta-for:artifact:Mixed Messaging" },
    { _id: "mfarMonsterMashaa", name: "meta-for:artifact:Monster Mash" },
    {
      _id: "mfarPuttingitALLT",
      name: "meta-for:artifact:Putting It All Together",
    },
    { _id: "mfarTheLabyrintha", name: "meta-for:artifact:The Labyrinth" },
    { _id: "mfarTownofTerrora", name: "meta-for:artifact:Town of Terror" },
    { _id: "reAviariaaaaaaaaa", name: "region:Aviaria" },
    { _id: "reAviariaaaaaaaaa", name: "region:Aviaria" },
    { _id: "reBubbLeCoveaaaaa", name: "region:Bubble Cove" },
    { _id: "reELandisLandsaaa", name: "region:Eland Islands" },
    { _id: "reELderDriftsaaaa", name: "region:Elder Drifts" },
    { _id: "reKittyCittyaaaaa", name: "region:Kitty Citty" },
    { _id: "reRoyaLGrovesaaaa", name: "region:Royal Groves" },
    { _id: "reSerpentineHiLLs", name: "region:Serpentine Hills" },
    { _id: "reTheBrightsaaaaa", name: "region:The Brights" },
    { _id: "reoLdBarkTownaaaa", name: "region:Old Bark Town" },
    { _id: "tycryptaaaaaaaaaa", name: "type:crypt" },
    { _id: "tyfLyingaaaaaaaaa", name: "type:flying" },
    { _id: "tyironaaaaaaaaaaa", name: "type:iron" },
    { _id: "tynormaLaaaaaaaaa", name: "type:normal" },
    { _id: "tysudokumonaaaaaa", name: "type:sudokumon" },
  ],
  puzzles: [
    {
      title: "Name That Tune",
      url: "https://puzzmon.world/puzzles/name_that_tune",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "NameThatTuneaaaaa",
      tags: ["diKingdomofthePuz", "arNameThatTuneaaa"],
    },
    {
      title: "Bird Nation",
      url: "https://puzzmon.world/puzzles/bird_nation",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "BirdNationaaaaaaa",
      tags: [
        "diKingdomofthePuz",
        "iscapstoneaaaaaaa",
        "reAviariaaaaaaaaa",
        "tyironaaaaaaaaaaa",
      ],
    },
    {
      title: "A Wanderer's Colorlog",
      url: "https://puzzmon.world/puzzles/a_wanderers_colorlog",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "AWanderersCoLorLo",
      tags: [
        "diKingdomofthePuz",
        "arCryptozooLogist",
        "reAviariaaaaaaaaa",
        "tysudokumonaaaaaa",
        "tyfLyingaaaaaaaaa",
      ],
    },
    {
      title: "Bird Calls",
      url: "https://puzzmon.world/puzzles/bird_calls",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "BirdCaLLsaaaaaaaa",
      tags: [
        "diKingdomofthePuz",
        "arTownofTerroraaa",
        "reAviariaaaaaaaaa",
        "tyfLyingaaaaaaaaa",
      ],
    },
    {
      title: "Exsportise",
      url: "https://puzzmon.world/puzzles/exsportise",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "Exsportiseaaaaaaa",
      tags: [
        "diKingdomofthePuz",
        "arTheLabyrinthaaa",
        "reAviariaaaaaaaaa",
        "tyironaaaaaaaaaaa",
      ],
    },
    {
      title: "Gen Nu Brain Rot",
      url: "https://puzzmon.world/puzzles/gen_nu_brain_rot",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "GenNuBrainRotaaaa",
      tags: [
        "diKingdomofthePuz",
        "arChartYourCourse",
        "reAviariaaaaaaaaa",
        "tyironaaaaaaaaaaa",
        "tyfLyingaaaaaaaaa",
      ],
    },
    {
      title: "Novelty Store",
      url: "https://puzzmon.world/puzzles/novelty_store",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "NoveLtyStoreaaaaa",
      tags: [
        "diKingdomofthePuz",
        "arTownofTerroraaa",
        "reAviariaaaaaaaaa",
        "tynormaLaaaaaaaaa",
      ],
    },
    {
      title: "Replacements",
      url: "https://puzzmon.world/puzzles/replacements",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "RepLacementsaaaaa",
      tags: [
        "diKingdomofthePuz",
        "arMonsterMashaaaa",
        "reAviariaaaaaaaaa",
        "tyironaaaaaaaaaaa",
      ],
    },
    {
      title: "Shopping Spree",
      url: "https://puzzmon.world/puzzles/shopping_spree",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "ShoppingSpreeaaaa",
      tags: [
        "diKingdomofthePuz",
        "arLetHerCookbooka",
        "reAviariaaaaaaaaa",
        "tysudokumonaaaaaa",
      ],
    },
    {
      title: "Welcome To MIT",
      url: "https://puzzmon.world/puzzles/welcome_to_mit",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "WeLcomeToMiTaaaaa",
      tags: [
        "diKingdomofthePuz",
        "arMixedMessaginga",
        "reAviariaaaaaaaaa",
        "tyironaaaaaaaaaaa",
      ],
    },
    {
      title: "Bringing Up Baby Shark",
      url: "https://puzzmon.world/puzzles/bringing_up_baby_shark",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "BringingupBabySha",
      tags: [
        "iscapstoneaaaaaaa",
        "diKingdomofthePuz",
        "reBubbLeCoveaaaaa",
        "tynormaLaaaaaaaaa",
      ],
    },
    {
      title: "Crossloop",
      url: "https://puzzmon.world/puzzles/crossloop",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "CrossLoopaaaaaaaa",
      tags: [
        "diKingdomofthePuz",
        "reBubbLeCoveaaaaa",
        "arMixedMessaginga",
        "tycryptaaaaaaaaaa",
      ],
    },
    {
      title: "Do They Have Chemistry? ",
      url: "https://puzzmon.world/puzzles/do_they_have_chemistry",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "DoTheyHaveChemist",
      tags: [
        "diKingdomofthePuz",
        "reBubbLeCoveaaaaa",
        "arChartYourCourse",
        "tycryptaaaaaaaaaa",
      ],
    },
    {
      title: "DROP * FROM Teams",
      url: "https://puzzmon.world/puzzles/drop_star_from_teams",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "DRoPFRoMTeamsaaaa",
      tags: [
        "diKingdomofthePuz",
        "reBubbLeCoveaaaaa",
        "arTheLabyrinthaaa",
        "tyironaaaaaaaaaaa",
      ],
    },
    {
      title: "Mechanical Soft Diet",
      url: "https://puzzmon.world/puzzles/mechanical_soft_diet",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "MechanicaLSoftDie",
      tags: [
        "diKingdomofthePuz",
        "reBubbLeCoveaaaaa",
        "arChartYourCourse",
        "tyfLyingaaaaaaaaa",
      ],
    },
    {
      title: "Somebody",
      url: "https://puzzmon.world/puzzles/somebody",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "Somebodyaaaaaaaaa",
      tags: [
        "diKingdomofthePuz",
        "reBubbLeCoveaaaaa",
        "arLetHerCookbooka",
        "tycryptaaaaaaaaaa",
      ],
    },
    {
      title: "This Puzzle Has Been Here The Whole Time",
      url: "https://puzzmon.world/puzzles/this_puzzle_has_been_here_the_whole_time",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "ThisPuzzLeHasBeen",
      tags: [
        "diKingdomofthePuz",
        "reBubbLeCoveaaaaa",
        "arMonsterMashaaaa",
        "tynormaLaaaaaaaaa",
      ],
    },
    {
      title: "Urban Angst",
      url: "https://puzzmon.world/puzzles/urban_angst",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "urbanAngstaaaaaaa",
      tags: [
        "diKingdomofthePuz",
        "reBubbLeCoveaaaaa",
        "arChartYourCourse",
        "tynormaLaaaaaaaaa",
        "tysudokumonaaaaaa",
      ],
    },
    {
      title: "Three Dog Night",
      url: "https://puzzmon.world/puzzles/three_dog_night",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "ThreeDogNightaaaa",
      tags: [
        "diKingdomofthePuz",
        "iscapstoneaaaaaaa",
        "reoLdBarkTownaaaa",
        "tycryptaaaaaaaaaa",
      ],
    },
    {
      title: "Balancing Act",
      url: "https://puzzmon.world/puzzles/balancing_act",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "BaLancingActaaaaa",
      tags: [
        "diKingdomofthePuz",
        "reoLdBarkTownaaaa",
        "arCryptozooLogist",
        "tycryptaaaaaaaaaa",
      ],
    },
    {
      title: "Central Precinct And Lockup",
      url: "https://puzzmon.world/puzzles/central_precinct_and_lockup",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "CentraLPrecinctAn",
      tags: [
        "diKingdomofthePuz",
        "reoLdBarkTownaaaa",
        "arTownofTerroraaa",
        "tyironaaaaaaaaaaa",
      ],
    },
    {
      title: "Pixelpinpointr",
      url: "https://puzzmon.world/puzzles/pixelpinpointr",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "PixeLpinpointraaa",
      tags: [
        "diKingdomofthePuz",
        "reoLdBarkTownaaaa",
        "arMonsterMashaaaa",
        "tynormaLaaaaaaaaa",
      ],
    },
    {
      title: "Spilled!",
      url: "https://puzzmon.world/puzzles/spilled",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "SpiLLedaaaaaaaaaa",
      tags: [
        "diKingdomofthePuz",
        "reoLdBarkTownaaaa",
        "arTownofTerroraaa",
        "tyfLyingaaaaaaaaa",
      ],
    },
    {
      title: "The Architecture Of Flow",
      url: "https://puzzmon.world/puzzles/the_architecture_of_flow",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "TheArchitectureof",
      tags: [
        "diKingdomofthePuz",
        "reoLdBarkTownaaaa",
        "arChartYourCourse",
        "tycryptaaaaaaaaaa",
      ],
    },
    {
      title: "Alchemy Academy",
      url: "https://puzzmon.world/puzzles/alchemy_academy",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "ALchemyAcademyaaa",
      tags: [
        "diKingdomofthePuz",
        "reKittyCittyaaaaa",
        "arTownofTerroraaa",
        "tynormaLaaaaaaaaa",
      ],
    },
    {
      title: "Nine Lives",
      url: "https://puzzmon.world/puzzles/nine_lives",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "NineLivesaaaaaaaa",
      tags: [
        "diKingdomofthePuz",
        "reKittyCittyaaaaa",
        "iscapstoneaaaaaaa",
        "tyfLyingaaaaaaaaa",
      ],
    },
    {
      title: "Capoo's Diary",
      url: "https://puzzmon.world/puzzles/capoos_diary",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "CapoosDiaryaaaaaa",
      tags: [
        "diKingdomofthePuz",
        "reKittyCittyaaaaa",
        "arLetHerCookbooka",
        "tyironaaaaaaaaaaa",
      ],
    },
    {
      title: "Cat-astrophe",
      url: "https://puzzmon.world/puzzles/cat_astrophe",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "Catastropheaaaaaa",
      tags: [
        "diKingdomofthePuz",
        "reKittyCittyaaaaa",
        "arMixedMessaginga",
        "tyironaaaaaaaaaaa",
      ],
    },
    {
      title: "Crafts Materials",
      url: "https://puzzmon.world/puzzles/crafts_materials",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "CraftsMateriaLsaa",
      tags: [
        "diKingdomofthePuz",
        "reKittyCittyaaaaa",
        "arChartYourCourse",
        "tycryptaaaaaaaaaa",
      ],
    },
    {
      title: "Jumping To Conclusions",
      url: "https://puzzmon.world/puzzles/jumping_to_conclusions",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "JumpingToConcLusi",
      tags: [
        "diKingdomofthePuz",
        "reKittyCittyaaaaa",
        "arTownofTerroraaa",
        "tyironaaaaaaaaaaa",
        "tyfLyingaaaaaaaaa",
      ],
    },
    {
      title: "Maps",
      url: "https://puzzmon.world/puzzles/maps",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "Mapsaaaaaaaaaaaaa",
      tags: [
        "diKingdomofthePuz",
        "reKittyCittyaaaaa",
        "arTheLabyrinthaaa",
        "tysudokumonaaaaaa",
      ],
    },
    {
      title: "Night Circus",
      url: "https://puzzmon.world/puzzles/night_circus",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "NightCircusaaaaaa",
      tags: [
        "diKingdomofthePuz",
        "reKittyCittyaaaaa",
        "arTownofTerroraaa",
        "tysudokumonaaaaaa",
      ],
    },
    {
      title: "Squint Your Ears",
      url: "https://puzzmon.world/puzzles/squint_your_ears",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "SquintYourEarsaaa",
      tags: [
        "diKingdomofthePuz",
        "reKittyCittyaaaaa",
        "arCryptozooLogist",
        "tynormaLaaaaaaaaa",
      ],
    },
    {
      title: "System of Operations",
      url: "https://puzzmon.world/puzzles/system_of_operations",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "Systemofoperation",
      tags: [
        "diKingdomofthePuz",
        "reKittyCittyaaaaa",
        "arCryptozooLogist",
        "tyironaaaaaaaaaaa",
        "tyfLyingaaaaaaaaa",
      ],
    },
    {
      title: "Watchtower",
      url: "https://puzzmon.world/puzzles/watchtower",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "Watchtoweraaaaaaa",
      tags: [
        "diKingdomofthePuz",
        "reKittyCittyaaaaa",
        "arTownofTerroraaa",
        "tyironaaaaaaaaaaa",
        "tysudokumonaaaaaa",
      ],
    },
    {
      title: "Puzzmon: The Card Game",
      url: "https://puzzmon.world/puzzles/puzzmon_the_card_game",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "PuTheCardGameaaaa",
      tags: [
        "diKingdomofthePuz",
        "iscapstoneaaaaaaa",
        "reELderDriftsaaaa",
        "tycryptaaaaaaaaaa",
      ],
    },
    {
      title: "Chemical X",
      url: "https://puzzmon.world/puzzles/chemical_x",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "ChemicaLXaaaaaaaa",
      tags: [
        "diKingdomofthePuz",
        "reELderDriftsaaaa",
        "arChartYourCourse",
        "tycryptaaaaaaaaaa",
      ],
    },
    {
      title: "Convalarium",
      url: "https://puzzmon.world/puzzles/convalarium",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "ConvaLariumaaaaaa",
      tags: [
        "diKingdomofthePuz",
        "reELderDriftsaaaa",
        "arTownofTerroraaa",
        "tyfLyingaaaaaaaaa",
      ],
    },
    {
      title: "Data Revisualization",
      url: "https://puzzmon.world/puzzles/data_revisualization",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "DataRevisuaLizati",
      tags: ["diKingdomofthePuz", "reELderDriftsaaaa", "tynormaLaaaaaaaaa"],
    },
    {
      title: "Financial Literacy",
      url: "https://puzzmon.world/puzzles/financial_literacy",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "FinanciaLLiteracy",
      tags: [
        "diKingdomofthePuz",
        "reELderDriftsaaaa",
        "arTownofTerroraaa",
        "tyironaaaaaaaaaaa",
      ],
    },
    {
      title: "Go Back to Square Fourteen",
      url: "https://puzzmon.world/puzzles/go_back_to_square_fourteen",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "GoBacktoSquareFou",
      tags: [
        "diKingdomofthePuz",
        "reELderDriftsaaaa",
        "arMonsterMashaaaa",
        "tyironaaaaaaaaaaa",
      ],
    },
    {
      title: "Method To The Mathmess",
      url: "https://puzzmon.world/puzzles/method_to_the_mathmess",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "MethodToTheMathme",
      tags: [
        "diKingdomofthePuz",
        "reELderDriftsaaaa",
        "arLetHerCookbooka",
        "tyfLyingaaaaaaaaa",
      ],
    },
    {
      title: "Nominative Determinism",
      url: "https://puzzmon.world/puzzles/nominative_determinism",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "NominativeDetermi",
      tags: [
        "diKingdomofthePuz",
        "reELderDriftsaaaa",
        "arCryptozooLogist",
        "tyironaaaaaaaaaaa",
        "tycryptaaaaaaaaaa",
      ],
    },
    {
      title: "Railway Terminal",
      url: "https://puzzmon.world/puzzles/railway_terminal",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "RaiLwayTerminaLaa",
      tags: [
        "diKingdomofthePuz",
        "reELderDriftsaaaa",
        "arTownofTerroraaa",
        "tysudokumonaaaaaa",
        "tyfLyingaaaaaaaaa",
      ],
    },
    {
      title: "Shapes",
      url: "https://puzzmon.world/puzzles/shapes",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "Shapesaaaaaaaaaaa",
      tags: [
        "diKingdomofthePuz",
        "reELderDriftsaaaa",
        "arMonsterMashaaaa",
        "tyfLyingaaaaaaaaa",
      ],
    },
    {
      title: "Tribute Puzzle",
      url: "https://puzzmon.world/puzzles/tribute_puzzle",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "TributePuzzLeaaaa",
      tags: [
        "diKingdomofthePuz",
        "reELderDriftsaaaa",
        "arCryptozooLogist",
        "tysudokumonaaaaaa",
      ],
    },
    {
      title: "Turing Machine",
      url: "https://puzzmon.world/puzzles/turing_machine",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "TuringMachineaaaa",
      tags: [
        "diKingdomofthePuz",
        "reELderDriftsaaaa",
        "arTheLabyrinthaaa",
        "tycryptaaaaaaaaaa",
      ],
    },
    {
      title: "Uneven",
      url: "https://puzzmon.world/puzzles/uneven",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "unevenaaaaaaaaaaa",
      tags: [
        "diKingdomofthePuz",
        "reELderDriftsaaaa",
        "arMixedMessaginga",
        "tysudokumonaaaaaa",
      ],
    },
    {
      title: "Clue Arbiter",
      url: "https://puzzmon.world/puzzles/clue_arbiter",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "CLueArbiteraaaaaa",
      tags: [
        "diKingdomofthePuz",
        "reTheBrightsaaaaa",
        "arMonsterMashaaaa",
        "tyironaaaaaaaaaaa",
      ],
    },
    {
      title: "Lights Down Mode",
      url: "https://puzzmon.world/puzzles/lights_down_mode",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "LightsDownModeaaa",
      tags: [
        "diKingdomofthePuz",
        "reTheBrightsaaaaa",
        "iscapstoneaaaaaaa",
        "tysudokumonaaaaaa",
      ],
    },
    {
      title: "Computation",
      url: "https://puzzmon.world/puzzles/computation",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "Computationaaaaaa",
      tags: [
        "diKingdomofthePuz",
        "reTheBrightsaaaaa",
        "arTownofTerroraaa",
        "tynormaLaaaaaaaaa",
      ],
    },
    {
      title: "Electrical Circuit",
      url: "https://puzzmon.world/puzzles/electrical_circuit",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "ELectricaLCircuit",
      tags: [
        "diKingdomofthePuz",
        "reTheBrightsaaaaa",
        "arChartYourCourse",
        "tyironaaaaaaaaaaa",
      ],
    },
    {
      title: "Haunted Mansion",
      url: "https://puzzmon.world/puzzles/haunted_mansion",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "HauntedMansionaaa",
      tags: [
        "diKingdomofthePuz",
        "reTheBrightsaaaaa",
        "arTownofTerroraaa",
        "tysudokumonaaaaaa",
        "tyfLyingaaaaaaaaa",
      ],
    },
    {
      title: "Musical Numbers",
      url: "https://puzzmon.world/puzzles/musical_numbers",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "MusicaLNumbersaaa",
      tags: [
        "diKingdomofthePuz",
        "reTheBrightsaaaaa",
        "arTheLabyrinthaaa",
        "tynormaLaaaaaaaaa",
      ],
    },
    {
      title: "Permutations",
      url: "https://puzzmon.world/puzzles/permutations",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "Permutationsaaaaa",
      tags: [
        "diKingdomofthePuz",
        "reTheBrightsaaaaa",
        "arMixedMessaginga",
        "tyfLyingaaaaaaaaa",
      ],
    },
    {
      title: "Pursuit of Liberty",
      url: "https://puzzmon.world/puzzles/pursuit_of_liberty",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "PursuitofLibertya",
      tags: ["diKingdomofthePuz", "reTheBrightsaaaaa", "tynormaLaaaaaaaaa"],
    },
    {
      title: "Rearranged",
      url: "https://puzzmon.world/puzzles/rearranged",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "Rearrangedaaaaaaa",
      tags: [
        "diKingdomofthePuz",
        "reTheBrightsaaaaa",
        "arCryptozooLogist",
        "tysudokumonaaaaaa",
      ],
    },
    {
      title: "Sound Translation",
      url: "https://puzzmon.world/puzzles/sound_translation",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "SoundTransLationa",
      tags: [
        "diKingdomofthePuz",
        "reTheBrightsaaaaa",
        "arTownofTerroraaa",
        "tyfLyingaaaaaaaaa",
      ],
    },
    {
      title: "Starry Night",
      url: "https://puzzmon.world/puzzles/starry_night",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "StarryNightaaaaaa",
      tags: [
        "diKingdomofthePuz",
        "reTheBrightsaaaaa",
        "arMonsterMashaaaa",
        "tynormaLaaaaaaaaa",
      ],
    },
    {
      title: "Ancestry",
      url: "https://puzzmon.world/puzzles/ancestry",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "Ancestryaaaaaaaaa",
      tags: ["diKingdomofthePuz", "reRoyaLGrovesaaaa", "tycryptaaaaaaaaaa"],
    },
    {
      title: "Filial Pie Tree",
      url: "https://puzzmon.world/puzzles/filial_pie_tree",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "FiLiaLPieTreeaaaa",
      tags: [
        "diKingdomofthePuz",
        "reRoyaLGrovesaaaa",
        "iscapstoneaaaaaaa",
        "tycryptaaaaaaaaaa",
      ],
    },
    {
      title: "Biology Research Exhibition",
      url: "https://puzzmon.world/puzzles/biology_research_exhibition",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "BioLogyResearchEx",
      tags: [
        "diKingdomofthePuz",
        "reRoyaLGrovesaaaa",
        "arChartYourCourse",
        "tynormaLaaaaaaaaa",
      ],
    },
    {
      title: "I Think That's Why They Call It That",
      url: "https://puzzmon.world/puzzles/i_think_thats_why_they_call_it_that",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "iThinkThatsWhyThe",
      tags: [
        "diKingdomofthePuz",
        "reRoyaLGrovesaaaa",
        "arMonsterMashaaaa",
        "tynormaLaaaaaaaaa",
        "tysudokumonaaaaaa",
      ],
    },
    {
      title: "Point of Divergence",
      url: "https://puzzmon.world/puzzles/point_of_divergence",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "PointofDivergence",
      tags: [
        "diKingdomofthePuz",
        "reRoyaLGrovesaaaa",
        "arMixedMessaginga",
        "tyironaaaaaaaaaaa",
      ],
    },
    {
      title: "Rock On",
      url: "https://puzzmon.world/puzzles/rock_on",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "Rockonaaaaaaaaaaa",
      tags: [
        "diKingdomofthePuz",
        "reRoyaLGrovesaaaa",
        "arTownofTerroraaa",
        "tycryptaaaaaaaaaa",
        "tysudokumonaaaaaa",
      ],
    },
    {
      title: "\ud83c\udf39Garden",
      url: "https://puzzmon.world/puzzles/rose_garden",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "Gardenaaaaaaaaaaa",
      tags: [
        "diKingdomofthePuz",
        "reRoyaLGrovesaaaa",
        "arTheLabyrinthaaa",
        "tycryptaaaaaaaaaa",
        "tynormaLaaaaaaaaa",
      ],
    },
    {
      title: "Strand-type Game",
      url: "https://puzzmon.world/puzzles/strand_type_game",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "StrandtypeGameaaa",
      tags: [
        "diKingdomofthePuz",
        "reRoyaLGrovesaaaa",
        "arLetHerCookbooka",
        "tyironaaaaaaaaaaa",
        "tysudokumonaaaaaa",
      ],
    },
    {
      title: "The Physics of Linguistic Fracture",
      url: "https://puzzmon.world/puzzles/the_physics_of_linguistic_fracture",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "ThePhysicsofLingu",
      tags: [
        "diKingdomofthePuz",
        "reRoyaLGrovesaaaa",
        "arChartYourCourse",
        "tyironaaaaaaaaaaa",
      ],
    },
    {
      title: "V-fun",
      url: "https://puzzmon.world/puzzles/v_fun",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "vfunaaaaaaaaaaaaa",
      tags: [
        "diKingdomofthePuz",
        "reRoyaLGrovesaaaa",
        "arCryptozooLogist",
        "tyfLyingaaaaaaaaa",
      ],
    },
    {
      title: "A Fake Artist Goes To Eland Islands",
      url: "https://puzzmon.world/puzzles/a_fake_artist_goes_to_eland_islands",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "AFakeArtistGoesTo",
      tags: ["diKingdomofthePuz", "reELandisLandsaaa", "tyfLyingaaaaaaaaa"],
    },
    {
      title: "Adding and Abutting",
      url: "https://puzzmon.world/puzzles/adding_and_abutting",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "AddingandAbutting",
      tags: [
        "diKingdomofthePuz",
        "reELandisLandsaaa",
        "arMixedMessaginga",
        "tyironaaaaaaaaaaa",
      ],
    },
    {
      title: "Gerrymandering",
      url: "https://puzzmon.world/puzzles/gerrymandering",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "Gerrymanderingaaa",
      tags: [
        "diKingdomofthePuz",
        "reELandisLandsaaa",
        "arTownofTerroraaa",
        "tyironaaaaaaaaaaa",
      ],
    },
    {
      title: "Hidden Numbers",
      url: "https://puzzmon.world/puzzles/hidden_numbers",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "HiddenNumbersaaaa",
      tags: [
        "diKingdomofthePuz",
        "reELandisLandsaaa",
        "arTheLabyrinthaaa",
        "tynormaLaaaaaaaaa",
        "tysudokumonaaaaaa",
      ],
    },
    {
      title: "Jam Session",
      url: "https://puzzmon.world/puzzles/jam_session",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "JamSessionaaaaaaa",
      tags: [
        "diKingdomofthePuz",
        "reELandisLandsaaa",
        "arTownofTerroraaa",
        "tyironaaaaaaaaaaa",
        "tysudokumonaaaaaa",
      ],
    },
    {
      title: "Keep Going! ",
      url: "https://puzzmon.world/puzzles/keep_going",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "KeepGoingaaaaaaaa",
      tags: [
        "diKingdomofthePuz",
        "reELandisLandsaaa",
        "arMixedMessaginga",
        "tysudokumonaaaaaa",
      ],
    },
    {
      title: "Linework",
      url: "https://puzzmon.world/puzzles/linework",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "Lineworkaaaaaaaaa",
      tags: [
        "diKingdomofthePuz",
        "reELandisLandsaaa",
        "arLetHerCookbooka",
        "tyironaaaaaaaaaaa",
        "tyfLyingaaaaaaaaa",
      ],
    },
    {
      title: "Loch Mystic",
      url: "https://puzzmon.world/puzzles/loch_mystic",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "LochMysticaaaaaaa",
      tags: [
        "diKingdomofthePuz",
        "reELandisLandsaaa",
        "arTownofTerroraaa",
        "tycryptaaaaaaaaaa",
      ],
    },
    {
      title: "Nailed It",
      url: "https://puzzmon.world/puzzles/nailed_it",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "NaiLeditaaaaaaaaa",
      tags: [
        "diKingdomofthePuz",
        "reELandisLandsaaa",
        "arMonsterMashaaaa",
        "tyironaaaaaaaaaaa",
        "tysudokumonaaaaaa",
      ],
    },
    {
      title: "People In The Main Block",
      url: "https://puzzmon.world/puzzles/people_in_the_main_block",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "PeopLeinTheMainBL",
      tags: [
        "diKingdomofthePuz",
        "reELandisLandsaaa",
        "arMixedMessaginga",
        "tyironaaaaaaaaaaa",
      ],
    },
    {
      title: "The Quaking Earth",
      url: "https://puzzmon.world/puzzles/the_quaking_earth",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "TheQuakingEarthaa",
      tags: [
        "diKingdomofthePuz",
        "reELandisLandsaaa",
        "arChartYourCourse",
        "tycryptaaaaaaaaaa",
      ],
    },
    {
      title: "Word Compression",
      url: "https://puzzmon.world/puzzles/word_compression",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "WordCompressionaa",
      tags: [
        "diKingdomofthePuz",
        "reELandisLandsaaa",
        "arCryptozooLogist",
        "tyironaaaaaaaaaaa",
      ],
    },
    {
      title: "Civil Service",
      url: "https://puzzmon.world/puzzles/civil_service",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "CiviLServiceaaaaa",
      tags: [
        "diKingdomofthePuz",
        "reSerpentineHiLLs",
        "arChartYourCourse",
        "tyfLyingaaaaaaaaa",
      ],
    },
    {
      title: "Australian Caduceus",
      url: "https://puzzmon.world/puzzles/australian_caduceus",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "AustraLianCaduceu",
      tags: [
        "diKingdomofthePuz",
        "reSerpentineHiLLs",
        "iscapstoneaaaaaaa",
        "tyironaaaaaaaaaaa",
      ],
    },
    {
      title: "Da' Bomb",
      url: "https://puzzmon.world/puzzles/da_bomb",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "DaBombaaaaaaaaaaa",
      tags: ["diKingdomofthePuz", "reSerpentineHiLLs", "tynormaLaaaaaaaaa"],
    },
    {
      title: "I Do (Not)",
      url: "https://puzzmon.world/puzzles/i_do_not",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "iDoNotaaaaaaaaaaa",
      tags: [
        "diKingdomofthePuz",
        "reSerpentineHiLLs",
        "arMixedMessaginga",
        "tyironaaaaaaaaaaa",
        "tynormaLaaaaaaaaa",
      ],
    },
    {
      title: "Minute Minute Cryptic",
      url: "https://puzzmon.world/puzzles/minute_minute_cryptic",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "MinuteMinuteCrypt",
      tags: [
        "diKingdomofthePuz",
        "reSerpentineHiLLs",
        "arCryptozooLogist",
        "tynormaLaaaaaaaaa",
      ],
    },
    {
      title: "Post-mortem Problems",
      url: "https://puzzmon.world/puzzles/post_mortem_problems",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "PostmortemProbLem",
      tags: [
        "diKingdomofthePuz",
        "reSerpentineHiLLs",
        "arTownofTerroraaa",
        "tynormaLaaaaaaaaa",
        "tyfLyingaaaaaaaaa",
      ],
    },
    {
      title: "Road Trip",
      url: "https://puzzmon.world/puzzles/road_trip",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "RoadTripaaaaaaaaa",
      tags: ["diKingdomofthePuz", "reSerpentineHiLLs", "tycryptaaaaaaaaaa"],
    },
    {
      title: "Watatsumi Shrine",
      url: "https://puzzmon.world/puzzles/watatsumi_shrine",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "WatatsumiShrineaa",
      tags: [
        "diKingdomofthePuz",
        "reSerpentineHiLLs",
        "arTownofTerroraaa",
        "tyironaaaaaaaaaaa",
      ],
    },
    {
      title: "Let Her Cook(book)",
      url: "https://puzzmon.world/puzzles/let_her_cookbook",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "LetHerCookbookaaa",
      tags: ["diKingdomofthePuz", "mfarLetHerCookboo"],
    },
    {
      title: "Mixed Messaging",
      url: "https://puzzmon.world/puzzles/mixed_messaging",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "MixedMessagingaaa",
      tags: ["diKingdomofthePuz", "mfarMixedMessagin"],
    },
    {
      title: "The Labyrinth",
      url: "https://puzzmon.world/puzzles/the_labyrinth",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "TheLabyrinthaaaaa",
      tags: ["diKingdomofthePuz", "mfarTheLabyrintha"],
    },
    {
      title: "Monster Mash",
      url: "https://puzzmon.world/puzzles/monster_mash",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "MonsterMashaaaaaa",
      tags: ["diKingdomofthePuz", "mfarMonsterMashaa"],
    },
    {
      title: "Cryptozoologist",
      url: "https://puzzmon.world/puzzles/cryptozoologist",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "CryptozooLogistaa",
      tags: ["diKingdomofthePuz", "mfarCryptozooLogi"],
    },
    {
      title: "Chart Your Course",
      url: "https://puzzmon.world/puzzles/chart_your_course",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "ChartYourCourseaa",
      tags: ["diKingdomofthePuz", "mfarChartYourCour"],
    },
    {
      title: "Town Of Terror",
      url: "https://puzzmon.world/puzzles/town_of_terror",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "TownofTerroraaaaa",
      tags: ["diKingdomofthePuz", "mfarTownofTerrora"],
    },
    {
      title: "Putting It All Together",
      url: "https://puzzmon.world/puzzles/putting_it_all_together",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "PuttingitALLToget",
      tags: ["diKingdomofthePuz", "mfarPuttingitALLT"],
    },
    {
      title: "Connect The Clans",
      url: "https://puzzmon.world/puzzles/connect_the_clans",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "ConnectTheCLansaa",
      tags: ["diKingdomofthePuz", "mfarConnecttheCLa"],
    },
    {
      title: "The Night Swatch",
      url: "https://puzzmon.world/puzzles/kingdom_runaround",
      expectedAnswerCount: 1,
      guesses: [],
      _id: "TheNightSwatchaaa",
      tags: ["diKingdomofthePuz", "isrunaroundaaaaaa", "ismetametaaaaaaaa"],
    },
  ],
};

export default FixtureHunt;
